### ISSUE TITLE
Receives ticket from the blocked user

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#108]
**Test Page :** Block Spam --> Blacklist User

**Bug :** All the tickets are receives from the blacklisted users.

**Steps to Reproduce Test :** 
**1.** Go to Dashboard and click on Block Spam icon

**2.** Enter any user's email address to Black List box : 
![screenshot](https://user-images.githubusercontent.com/43210406/51476112-85538580-1daa-11e9-98cc-1347d1d89979.png)

**3.** Block User generate ticket , and receives on support helpdesk.

![screenshot](https://user-images.githubusercontent.com/43210406/51476431-876a1400-1dab-11e9-9f20-1773998db27f.png)

**Comment by papnoisanjeev** [comment]
fixed.
