### ISSUE TITLE
Update collaborator warning message when add existing collaborator at admin panel

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#124]
### Update warning as:  "collaborator is already added"  
by replacing current warning message which should show only when customer added not a collaborator.

![screenshot 97](https://user-images.githubusercontent.com/43210406/51906079-1e0c8580-23e9-11e9-9ef6-7675256787f9.png)

**Comment by papnoisanjeev** [comment]
fixed
