### ISSUE TITLE
Upgrade dependencies 

### ISSUE THREAD

**Issue by FBL-dev** [uvdesk/core-framework#137]
` Problem 1
    - uvdesk/core-framework 0.1.x-dev requires symfony/asset ^3.4 -> no matching package found.
    - uvdesk/core-framework 0.1.x-dev requires symfony/asset ^3.4 -> no matching package found.
    - Installation request for uvdesk/core-framework ^0.1.0@dev -> satisfiable by uvdesk/core-framework[0.1.x-dev].`

**Comment by vaishaliwebkul** [comment]
Hi FlorianBenLamine,
  
  Please share your system environment variable along with **php version** under which you are facing such kind of dependencies issues.
