### ISSUE TITLE
Image not get insert by option given in rich text editor at the time of reply to any ticket

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#14]
**Target Page :** Ticket List

**Issue Found:** Add image by given option to attach image in rich text editor while reply to ticket detail as given below : 

**Image unable to attach**

![screenshot 12](https://user-images.githubusercontent.com/43210406/50148496-b0941200-02de-11e9-8fdc-2ca9ba1bd02b.png)

**Comment by shubhwebkul** [comment]
add attachment option on editor has been removed
