### ISSUE TITLE
Opened sections available in dashboards are not showing in bold

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#140]
![screenshot69](https://user-images.githubusercontent.com/43210406/59082125-33516d80-890f-11e9-9510-470c0a99aaa8.png)

**Comment by kumarSaurabh27** [comment]
Resolved   https://github.com/uvdesk/core-framework/pull/139

**Comment by kumarSaurabh27** [comment]
updated and resolved https://github.com/uvdesk/core-framework/pull/139

**Comment by vaishaliwebkul** [comment]
**Reproduce Issue:**

Swiftmailer-> edit swiftmailer -> observe side menu bar
![bold](https://user-images.githubusercontent.com/43210406/60071598-4dc17e80-9738-11e9-9432-250a98c59d5d.png)
