### ISSUE TITLE
Is there any option to change admin panel logo??

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#141]
### likewise knowledgebase logo update, there must be an option available to update admin panel logo!!

![Screenshot70](https://user-images.githubusercontent.com/43210406/59093417-863c1c80-8931-11e9-9a6a-a27abebb1274.png)

**Comment by kumarSaurabh27** [comment]
Resolved https://github.com/uvdesk/core-framework/pull/144

**Comment by vaishaliwebkul** [comment]
Default logo is not set.

![Screenshot87](https://user-images.githubusercontent.com/43210406/60000555-155f6900-9682-11e9-8e28-da0d51793b86.png)

**Comment by kumarSaurabh27** [comment]
Fixed.
