### ISSUE TITLE
Once installation is completed wizard still shows

### ISSUE THREAD

**Issue by kruisdraad** [uvdesk/core-framework#146]
The installer should not be available after installation. The installer can be re-run on a live installation which an attacker might use to compromise the system as it allows to create a new superadmin

**Comment by shubhwebkul** [comment]
Hi kruisdraad,
You might execute web installer as many times you want but you could disable it by redirecting all the requests from uvdesk web installer to knowledgebase with the help of a route.

In our upcoming version, we'll add this route by default if web installer is completed once.

for help, you could refer here #community-skeleton/153

Redirection route to be added in uvdesk.yaml resides in routes directory under config. (with proper indentation):-
uvdesk_support_center_bundle_use_locale:
path: /
controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
defaults:
path: /en/
permanent: true
