### ISSUE TITLE
Exception on Branding and email settings section

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#150]
**Branding section, throw error**

![Screenshot85](https://user-images.githubusercontent.com/43210406/59997181-fe1c7d80-9679-11e9-8341-58dcf5938320.png)

**Email Settings, Result not found**
![Screenshot86](https://user-images.githubusercontent.com/43210406/59997286-581d4300-967a-11e9-8cc3-d4e3d69cfe64.png)

**Comment by papnoisanjeev** [comment]
https://github.com/uvdesk/core-framework/pull/149

**Comment by papnoisanjeev** [comment]
fixed
