### ISSUE TITLE
wrong workflow set for event "ticket create"

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#152]
When **Ticket Created** set action as:

**mail to customer -> ticket generated success message
assign to agent-> superadmin(default)
mail to assign agent-> superadmin(for this case)**

update first action which is Actual 
**mail to customer -> account created mail**

expected
**mail to customer -> ticket generated success message**

**Comment by papnoisanjeev** [comment]
Default workflow action made as per requirement.
fixed.
