### ISSUE TITLE
Customer account create email template placeholder issue

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#153]
Check mail content receives to the customer for account creation.

**Case:**
Verifies that the new customer receives correct email content when an agent creates a ticket from their panel.

**Mail content receives by customer**
Placeholder is not working in customer account create email template
![Screenshot90](https://user-images.githubusercontent.com/43210406/60070488-83646880-9734-11e9-8af3-94a54ffac575.png)

**Comment by papnoisanjeev** [comment]
fixed
