### ISSUE TITLE
Customer status set inactive when created from website 

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#164]
### New customer status is inactive 

Customer was created from website by generating ticket

![bold4](https://user-images.githubusercontent.com/43210406/60584456-f2803380-9daa-11e9-9e3c-4f08e153ba8d.png)

**Comment by papnoisanjeev** [comment]
Fixed

**Comment by vaishaliwebkul** [comment]
When customer added as collaborator inside ticket, customer status gets inactive, please check
