### ISSUE TITLE
Update Layout design

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#174]
1. Update dropdown-menu icon which gets open when clicking on Uvdesk admin profile

2. uv-active sidebar must be highlighted with theme color

3. Checkbox place on ticket list to select multiple ticket is not in right place.

**Comment by vaishaliwebkul** [comment]
@vaishaliwebkul 
issue 1 or 3 has been resolved, still need to fix issue 2

uv-active sidebar must be highlighted with theme color

https://www.loom.com/share/2a5a43aeba774adbbf896e85040ddef2

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed [here ](https://github.com/uvdesk/core-framework/commit/1889af463a4e0eb08f3394583469d246fac2291b) in master.

**Comment by vaishaliwebkul** [comment]
fixed
