### ISSUE TITLE
Error on Email settings

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#187]
Framework Version 1.0

When rendering on email settings, the issue comes as shown in the screenshot:

![awesome5](https://user-images.githubusercontent.com/43210406/62305486-b28d9880-b49d-11e9-9404-bca539c69d83.png)

**Comment by akshaywebkul** [comment]
Fixed with commit [c08f965](https://github.com/uvdesk/core-framework/commit/c08f96524affbe0a156bc263686a9e2477ae279c).
