### ISSUE TITLE
Attempt load language dropdown changer after reply on ticket

### ISSUE THREAD

**Issue by maranqz** [uvdesk/core-framework#192]
support/vendor/uvdesk/core-framework/Resources/views/ticketList.html.twig:uv-dropdown-list uv-bottom-left uv-translate-list

You did not full cut the feature with changing language from ticket.
Page attempts load icons of language but they do not exist.

**Comment by papnoisanjeev** [comment]
**support/vendor/uvdesk/core-framework/Resources/views/ticket.html.twig**  we are fetching flags for all locale and we have not added flag icon. you can remove 
![ticket](https://user-images.githubusercontent.com/42460055/63319632-60bb8e00-c338-11e9-9612-fedb1a085332.png) this code from ticket.html.twig for now. we will use this when we use lang feature.

we will use these things when we use language feature.
