### ISSUE TITLE
Mailbox not found in PROD environment

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#200]
**Framework Version 1.0**

to get the tickets list we need to run the CRON job every time and keep the APP_ENV=dev in .env file. If we run the CRON job after changing the mode to PROD, it fails saying the mailbox not found.

Also the same happens when unable to clear project's cache

![prod_issue](https://user-images.githubusercontent.com/43210406/64613731-81857980-d3f4-11e9-840b-0ae97d48821c.png)

**Comment by maquowicz** [comment]
Looks like current dev stability has this issue still unresolved. 
Reproduce:
1. composer create-project uvdesk/community-skeleton helpdesk-project --stability dev
2. switch .env to prod
3. bin/console c:c throws: You have requested a non-existent service "swiftmailer.mailer".

Workaround: 
1. create config/packages/prod/swiftmailer.yaml with some default settings:
`swiftmailer:
    disable_delivery: false`

**Comment by piyushwebkul** [comment]
Could not reproduce? Could you post the content of swiftmailer.yaml

**Comment by maquowicz** [comment]
Without **config/packages/prod/swiftmailer.yaml** issue persists. Once created at this location it loads mailer component properly. Content is generic, prob also just `swiftmailer:` would do. Mine looks like that:
```
swiftmailer:
    disable_delivery: false
```
Not sure if its relative but my env is Ubuntu 18, php7.2, nginx, Composer version 1.8.4

**Comment by piyushwebkul** [comment]
@maquowicz 

I tried removing all `swiftmailer.yaml` files from config directory including prod, dev, and test, but did not find any errors. It seems that if your swiftmailer.yaml file contains invalid configuration parameters the `swiftmailer.mailer` alias won't get registered with the container, which in turn spit the service not found error. 

When you executed `composer create-project`  command what was exactly the content of your swiftmailer.yaml file (all env dev/prod/test)?
Your symfony swiftmailer-bundle version?
Also, could you post a snapshot or contents of the error message?

**Comment by maquowicz** [comment]
Originally created project with this:
`composer create-project uvdesk/community-skeleton helpdesk-project --stability dev`

Now moved HEAD back to 'initialise repo with project files'.
./config/packages/prod/swiftmailer.yaml is now gone

swiftmailer version v6.2.1

got APP_ENV=dev in PROJECT_ROOT/.env
![Screenshot from 2019-11-05 11-44-33](https://user-images.githubusercontent.com/10026557/68201343-e3f89180-ffc1-11e9-8c35-f70392cae634.png)

switched APP_ENV=dev to APP_ENV=prod in PROJECT_ROOT/.env
![Screenshot from 2019-11-05 11-51-52](https://user-images.githubusercontent.com/10026557/68202462-14412f80-ffc4-11e9-8837-d793ce5fe61e.png)
Also unable to reproduce now. It works in both envs even on my newest commit without ./config/packages/prod/swiftmailer.yaml 

Might was just a glitch, sorry for the trouble. Will report if spotted again.

**Comment by piyushwebkul** [comment]
It was probably related to symfony/swiftmailer-bundle, as it parses the configuration in swiftmailer.yaml and registers the `default_mailer` as `swiftmailer.mailer` only if `default_mailer = =swifmailer.mailer.some_mailer` where `some_mailer` refers to a `mailer` from `mailers` property in swiftmailer.yaml. To put it simply, If default_mailer doesn't match any mailers, `SwiftmailerExtension` won't alias `swiftmailer.mailer` which in turn spit that error
