### ISSUE TITLE
submit button need more options for ROLE_AGENT

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#227]
**Description**

Agents click on the reply button, gets submit option available, there should be more options added as below mention list 

> Submit And Open
> Submit And Pending
> Submit And Answered
> Submit And Resolved
> Submit And Closed

**Reproduce**
1. Login to an agent panel
2. Open or view ticket page
3. check the reply button options

![submit](https://user-images.githubusercontent.com/43210406/66648578-7a4ac900-ec49-11e9-8d5a-e95c23dc4fe9.png)

**Comment by princewebkul** [comment]
you can set  'can update ticket status' privilege for agent in privileges section then agent will get more submit options on reply button.
