### ISSUE TITLE
Will API realisation?

### ISSUE THREAD

**Issue by maranqz** [uvdesk/core-framework#229]
Hello.

May you realize the [API ](https://www.uvdesk.com/en/api-doc/) like you did in paid version. 
If it is yes when will  it be published?
May i help to do it?

**Comment by papnoisanjeev** [comment]
Yes, definitely we will release API for opensource version.
Currently API part under development process we will try to release it soon.

want to discuss more with developer talk, catch us @ https://gitter.im/uvdesk/community
