### ISSUE TITLE
IMAP Mailbox Not Creating Tickets

### ISSUE THREAD

**Issue by knockturnlabs** [uvdesk/core-framework#231]
Setting up IMAP works just fine. However, e-mails are not created in the ticketing system even though the console job states that it's working::

root@ubuntu:/var/www/html/uvdesk# php -e bin/console uvdesk:refresh-mailbox zgould@knockturnlabs.com

 1. Processing uvdesk mailbox configuration.

 2. Opening imap stream...

 3. IMAP stream opened.

 4. Fetching Email collection since 13 October 2019.

 5. Total fetched email -> 1

 6. Starting to convert Emails into Tickets ->
=============================================
=============================================

  Converting email 1 out of 1.

 Mailbox refreshed successfully !!!

**Comment by papnoisanjeev** [comment]
@knockturnlabs,it seems site url is not correct.
open **uvdesk.yaml** file and check your site url.

Also you can check the blog if something is missing.
https://www.uvdesk.com/en/blog/setup-mailbox-uvdesk-open-source-helpdesk/

**Comment by vaishaliwebkul** [comment]
Hi @knockturnlabs,
 
 Any Update?
