### ISSUE TITLE
Unable to update status of ticket when add a note to ticket 

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#24]
Bug : ticket status is not get updated when note is added to the ticket .
Case 1: When select submit and resolved then status not get updated
![screenshot 68](https://user-images.githubusercontent.com/43210406/50421272-7e952980-0863-11e9-98a5-95277cc92d60.png)

**Comment by shubhwebkul** [comment]
resolved

**Comment by vaishaliwebkul** [comment]
Please check again as when note is added to ticket by select **submit and resolved**, ticket status update as **answered status** instead **Resolved**
![screenshot 76](https://user-images.githubusercontent.com/43210406/50503995-98678400-0a90-11e9-9f56-f39445123156.png)
