### ISSUE TITLE
super admin name is not showing when set via terminal

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#240]
Setting up the super admin name[first_name] and email from the terminal.
Observe that inside ticket view no name listed with super admin profile.

![test1](https://user-images.githubusercontent.com/43210406/67096278-610bc480-f1d5-11e9-937b-8fa5d957870c.png)

**Comment by vaishaliwebkul** [comment]
@anmol107 
This issue not fixed yet.
I set the agent first name via terminal, but agent name still not show in **ticket list**, **quick view trigger page**

**Comment by anmol107** [comment]
#240 
Admin/Agent name not showing when the last name of the Agent/Admin is empty (null inside the database), thus rendering the full-name of the Agent/Admin as an empty string inside the twig template.
