### ISSUE TITLE
Exception occur while executing action {mail to agent:repsonse performing agent}

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#260]
**Issue Type:** 
-Workflow Issue

**Environment**
-Prod/dev

**Steps to Reproduce**

**Step 1-** 
Set workflow as 
-{Name: Ticket group update}
-{Event: ticket->Note Added}
-{Action: Mail to Agent: Response Performing Agent}
**Step-2** 
Execute the mention workflow's event on any ticket
You will be getting an exception as mention below screenshot:

**Screenshot of Bug**
![Screenshot (1)](https://user-images.githubusercontent.com/43210406/68101690-e9d47100-fef4-11e9-9a88-949c6b87d716.png)

**Comment by papnoisanjeev** [comment]
Fixed
