### ISSUE TITLE
Ticket link attach with message body on agent's mail id redirect to wrong panel

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#27]
Agent receives any notification message regarding ticket will receives mail on their given mail id which mail contains ticket link.
**When agent click on that link will redirect to customer panel instead of member panel. **
![screenshot 71](https://user-images.githubusercontent.com/43210406/50443758-c6cb4f00-092a-11e9-9289-8bb6407c08c1.png)

**Comment by shubhwebkul** [comment]
resolved

**Comment by shubhwebkul** [comment]
#32
