### ISSUE TITLE
Uvdesk mail configure error

### ISSUE THREAD

**Issue by jaganpandya** [uvdesk/core-framework#273]
Hi All, i have opensource uvdesk. uvdesk installed in windows and as per youtube video i done all the setting but i cannot get the email from the gmail as ticket in my uvdesk. see the image i uploaded. it
shows the successfully done but ticket is not open. Please guide me what can i do for this.

![test](https://user-images.githubusercontent.com/58220630/69638850-87990700-1081-11ea-90f8-9ef344a1890a.png)

**Comment by vaishaliwebkul** [comment]
Hi @jaganpandya,
   please show the uvdesk.yaml file for site_url

**Comment by jaganpandya** [comment]
Hi, @vaishaliwebkul  

Thanks for the reply here i attach  uvdesk.yaml file. please check it and guide me for the same.
Thank you

**Comment by jaganpandya** [comment]
Please check this and guide me for the same.

Thank you

**Comment by vaishaliwebkul** [comment]
please attach the file again as we didn't get it, or also you can share the screenshots.

**Comment by jaganpandya** [comment]
Please check this file i converted it in .txt file. so,please guide me for this.

[uvdesk.txt](https://github.com/uvdesk/core-framework/files/3896827/uvdesk.txt)

**Comment by vaishaliwebkul** [comment]
Always keep the site_url accessible to the project's public folder without slash / at the end of the url

update the url inside uvdesk.yaml as mention below: 

**site_url: 'localhost/localhost/uvdesk/uvdesk-community-v1.0.5/public'**

Next, clear cache: **php bin/console c:c**
Now, run mailbox refresh command: php bin/console uvdesk:refresh-mailbox xyz@domain.com

**Comment by papnoisanjeev** [comment]
@jaganpandya 
Most probably your site url should be.
**site_url:  http://localhost/uvdesk/uvdesk-community-v1.0.5/public**

Clear your project cache after this:
**php bin/console c:c**

If you still face problem then go to your project root directory find:
**vendor->uvdesk->automation-bundle->mailbox-component->RefreshMailboxCommand.php**

Open RefreshMailboxCommand.php file find pushMessage() function  and **dump($curlResponse); die;**  and debug what problem you are facing and let us know curl response.

**Comment by jaganpandya** [comment]
i done @vaishaliwebkul  and @papnoisanjeev  i got the below error. i attach this file.
![test2](https://user-images.githubusercontent.com/58220630/69724811-a90df780-1142-11ea-99c9-6d94a88c6eff.png)

**Comment by papnoisanjeev** [comment]
@jaganpandya
Please check if your **Imap Extension** is enabled or not.

Check these links too.
https://stackoverflow.com/questions/48179146/attempted-to-call-function-imap-open-from-namespace
https://www.php.net/manual/en/function.imap-open.php

**Comment by jaganpandya** [comment]
i done already below both the option.

    Gmail less secured app config
    Imap for gmail.
 i got the below error screenshot is here.
![test5](https://user-images.githubusercontent.com/58220630/69805840-96112b00-1207-11ea-80ba-4500d1f0997c.png)

**Comment by vaishaliwebkul** [comment]
@jaganpandya 

it looks error calls as IMAP found invalid credentials of your mailbox.
try with **enter valid #email id and #password** in uvdesk_mailbox.yaml,swiftmailer.yaml.
also, verify the less secure app must be enabled.

**Comment by papnoisanjeev** [comment]
@jaganpandya  

If still you face problem, please create a support ticket on 
https://support.uvdesk.com/en/customer/create-ticket/  

We will provide you the best possible support.

**Comment by jaganpandya** [comment]
i am using gmail email id and done imap setting in gmail and also on less secure app.
error in file refreshmailboxcommand file where imap_open() is used. plese guide me. what can i do now?
thank you

**Comment by vaishaliwebkul** [comment]
To operating this error, please browse to the info.php and search for imap.ini in additional .ini files parsed if it is not there, it means that PHP is not listening to the IMAP module. Please do the following mention below points:-

- dump() function in RefreshMailboxCommand.php, if exist please remove

- search for IMAP in info.php file, it should exist or enabled.

- Restart apache service httpd -k restart

Now, please execute the refresh mailbox command again.

**Comment by vaishaliwebkul** [comment]
@jaganpandya 
   Your query has been resolved in our support panel, so we are closing this ticket.

**Comment by rcpearcentu** [comment]
Solution:

Attempted to call function "imap_open" from namespace "Webkul\UVDesk\MailboxBundle\Console".
  
  
  We found a solution:

 I cant explain how this fixes the problem but it did seem to.

despite PHP reporting that imap extension is installed and me confirming it works by running a test script in the browser it wasnt working on the command line. So,basically reinstalled imap and dependancy php-curl (See below the steps for Linux but i would imagine the same principle should work for Windows. The odd thing is those extensions were installed - so maybe it was an update that was required.   my guess is the browser may be running php 7.3 (IMAP works for the browser) but the command line is using php 7.4 which didnt have imap and curl extensions installed. I ended up with two versions of php quite by accident - i dont know how 7.4 got on my server

sudo apt install php-imap
  463  sudo phpenmod imap
  464  sudo apt update
  465  sudo apt
  467  sudo apt upgrade -y
  468  sudo reboot
  469  sudo apt update
  470  sudo apt upgrade
  471  sudo apt autoremove
  472  sudo reboot
  477  sudo add-apt-repository ppa:ondrej/php
  478  sudo apt-get update
  479  sudo apt-get install php-curl

**Comment by papnoisanjeev** [comment]
@rcpearcentu  

>**my guess is the browser may be running php 7.3 (IMAP works for the browser) but the command line is using php 7.4**

Glad to know that you found your issue.
Exactly, It was the reason behind this issue.

**Comment by emtized** [comment]
Same Problem with php 7.2

**Comment by Akila1996522** [comment]
![image](https://github.com/uvdesk/core-framework/assets/54936379/5be3678b-eaaa-4921-9c1f-f926b0e146fd)
What is this error and how to solve this error?

**Comment by Komal-sharma-2712** [comment]
@Akila1996522 ,

As per shared your screenshots looks like refresh email address: no such mailbox. Please verify once your email address and also saved setting again with correct email in mailbox configuration setting.

Kind Respects
Uvdesk Team
