### ISSUE TITLE
error when ticket is created - mail to customer not sent

### ISSUE THREAD

**Issue by laurentiu2** [uvdesk/core-framework#277]
**Description**  
When a customer creates a ticket for the first time, via mail or web, there are two workflows active:
- one to create the customer account and send an email to customer,
- one to create the ticket and send an email to customer.

When the customer creates the ticket by mail everything works fine.
When the customer creates the ticket by web, the first workflow executes completely, the second workflow creates the ticket but does not send the email.
When an agent creates the ticket for a new/existing customer within the application, only the first workflow is executed entirely.
For the second workflow, the ticket gets created, but the email with the response no.

**How to reproduce**  
Create a ticket for a new/existing customer within the app, while logged in as agent.

I don't know what else info to provide.
My conditions for the second workflow: 
- if TYPE is equal to 
or
- if TO EMAIL is equal to

I suppose the first condition is not verified.
Regards,

![Screenshot 2020-01-06 at 20 01 10](https://user-images.githubusercontent.com/29857699/71837593-7d761980-30bf-11ea-8f75-1bf470e724d1.png)
![Screenshot 2020-01-06 at 20 01 28](https://user-images.githubusercontent.com/29857699/71837592-7cdd8300-30bf-11ea-8b58-ef99c2d7a5d0.png)

**Comment by papnoisanjeev** [comment]
@laurentiu2 
Thanks for reporting this bug. It will be removed in next release.
For now you can fix this issue in your code, locate to the file

****vendor->uvdesk->core-framework->Workflow->Actions->Ticket->MailCustomer.php**

Open **MailCustomer.php** and  reach to **applyAction()**  function.

Now add these 2 lines in your code which which we have added with the red mark in the screenshot.

![mailtocustomer](https://user-images.githubusercontent.com/42460055/71887395-00e94680-3164-11ea-9b76-3ce46b35154a.png)

**Comment by laurentiu2** [comment]
Thanks!!
It works.
👍😄

**Comment by papnoisanjeev** [comment]
@laurentiu2 
If you found any other issue while using our software you can easily create a support ticket.
https://support.uvdesk.com/en/customer/create-ticket/   here.
