### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Notice: Undefined variable: configuration").

### ISSUE THREAD

**Issue by fernandogiacomino** [uvdesk/core-framework#278]
![doctrine](https://user-images.githubusercontent.com/20728688/72665367-a0b99680-39e6-11ea-92d1-aa60c5dc6f4a.JPG)
Version 1.0.4 on linux shared hosting ifastnet. Auto-installation ok, when I call Admin Panel or Knowledgebase first time throw this error.
------------------------------------
`

Twig\Error\RuntimeError: An exception has been thrown during the rendering of a template ("Notice: Undefined variable: configuration").    at /home/users/sanjeev.papnoi/www/html/UVDeskOSZIp/uvdesk-community-v1.0.6/vendor/uvdesk/core-framework/Resources/views/Templates/layout.html.twig:14   at Twig\Template->displayWithErrorHandling(array('last_username' => '', 'error' => null, 'app' => object(AppVariable), 'default_agent_image_path' => 'bundles/uvdeskcoreframework/images/uv-avatar-batman.png', 'default_customer_image_path' => 'bundles/uvdeskcoreframework/images/uv-avatar-ironman.png', 'default_helpdesk_image_path' => 'bundles/uvdeskcoreframework/images/uv-avatar-uvdesk.png', 'max_post_size' => 8388608, 'max_file_uploads' => 20, 'upload_max_filesize' => 2097152, 'user_service' => object(UserService), 'uvdesk_service' => object(UVDeskService), 'ticket_service' => object(TicketService), 'csrf_token_generator' => object(CsrfTokenManager), 'email_service' => object(EmailService), 'uvdesk_extensibles' => object(ExtendableComponentManager), 'uvdesk_core_file_system' => object(FileSystem), 'uvdesk_automations' => object(AutomationService)), array('title' => array(object(__TwigTemplate_52888b8f1b26e6c9a6085f15453384cebcadf7e6832fbc88ce0564edc691bd73), 'block_title'), 'templateCSS' => array(object(__TwigTemplate_52888b8f1b26e6c9a6085f15453384cebcadf7e6832fbc88ce0564edc691bd73), 'block_templateCSS'), 'sidebar' => array(object(__TwigTemplate_0eeb869595ecd9118938f65e6c709568b42f54c67601260bde46f2d92cd49e85), 'block_sidebar'), 'pageWrapper' => array(object(__TwigTemplate_52888b8f1b26e6c9a6085f15453384cebcadf7e6832fbc88ce0564edc691bd73), 'block_pageWrapper'), 'pageHeader' => array(object(__TwigTemplate_0eeb869595ecd9118938f65e6c709568b42f54c67601260bde46f2d92cd49e85), 'block_pageHeader'), 'pageContent' => array(object(__TwigTemplate_0eeb869595ecd9118938f65e6c709568b42f54c67601260bde46f2d92cd49e85), 'block_pageContent'), 'footer' => array(object(__TwigTemplate_52888b8f1b26e6c9a6085f15453384cebcadf7e6832fbc88ce0564edc691bd73), 'block_footer')))      (vendor/twig/twig/src/Template.php:380)   at Twig\Template->display(array('last_username' => '', 'error' => null, 'app' => object(AppVariable), 'default_agent_image_path' => 'bundles/uvdeskcoreframework/images/uv-avatar-batman.png', 'default_customer_image_path' => 'bundles/uvdeskcoreframework/images/uv-avatar-ironman.png', 'default_helpdesk_image_path' => 'bundles/uvdeskcoreframework/images/uv-avatar-uvdesk.png', 'max_post_size' => 8388608, 'max_file_uploads' => 20, 'upload_max_filesize' => 2097152, 'user_service' => object(UserService), 'uvdesk_service' => object(UVDeskService), 'ticket_service' => object(TicketService), 'csrf_token_generator' => object(CsrfTokenManager), 'email_service' => object(EmailService), 'uvdesk_extensibles' => object(ExtendableComponentManager), 'uvdesk_core_file_system' => object(FileSystem), 'uvdesk_automations' => object(AutomationService)), array('title' => array(object(__TwigTemplate_52888b8f1b26e6c9a6085f15453384cebcadf7e6832fbc88ce0564edc691bd73), 'block_title'), 'templateCSS' => array(object(__TwigTemplate_52888b8f1b26e6c9a6085f15453384cebcadf7e6832fbc88ce0564edc691bd73), 'block_templateCSS'), 'pageWrapper' => array(object(__TwigTemplate_52888b8f1b26e6c9a6085f15453384cebcadf7e6832fbc88ce0564edc691bd73), 'block_pageWrapper'), 'footer' => array(object(__TwigTemplate_52888b8f1b26e6c9a6085f15453384cebcadf7e6832fbc88ce0564edc691bd73), 'block_footer')))      (var/cache/dev/twig/9f/9f0472ec0f65654b8746b08184e8a7e8dc1981f8bd90a1fd5960535e015a510f.php:51)   at __TwigTemplate_52888b8f1b26e6c9a6085f15453384cebcadf7e6832fbc88ce0564edc691bd73->doDisplay(array('last_username' => '', 'error' => null, 'app' => object(AppVariable), 'default_agent_image_path' => 'bundles/uvdeskcoreframework/images/uv-avatar-batman.png', 'default_customer_image_path' => 'bundles/uvdeskcoreframework/images/uv-avatar-ironman.png', 'default_helpdesk_image_path' => 'bundles/uvdeskcoreframework/images/uv-avatar-uvdesk.png', 'max_post_size' => 8388608, 'max_file_uploads' => 20, 'upload_max_filesize' => 2097152, 'user_service' => object(UserService), 'uvdesk_service' => object(UVDeskService), 'ticket_service' => object(TicketService), 'csrf_token_generator' => object(CsrfTokenManager), 'email_service' => object(EmailService), 'uvdesk_extensibles' => object(ExtendableComponentManager), 'uvdesk_core_file_system' => object(FileSystem), 'uvdesk_automations' => object(AutomationService)), array('title' => array(object(__TwigTemplate_52888b8f1b26e6c9a6085f15453384cebcadf7e6832fbc88ce0564edc691bd73), 'block_title'), 'templateCSS' => array(object(__TwigTemplate_52888b8f1b26e6c9a6085f15453384cebcadf7e6832fbc88ce0564edc691bd73), 'block_templateCSS'), 'pageWrapper' => array(object(__TwigTemplate_52888b8f1b26e6c9a6085f15453384cebcadf7e6832fbc88ce0564edc691bd73), 'block_pageWrapper'), 'footer' => array(object(__TwigTemplate_52888b8f1b26e6c9a6085f15453384cebcadf7e6832fbc88ce0564edc691bd73), 'block_footer')))      (vendor/twig/twig/src/Template.php:407)   at Twig\Template->displayWithErrorHandling(array('last_username' => '', 'error' => null, 'app' => object(AppVariable), 'default_agent_image_path' => 'bundles/uvdeskcoreframework/images/uv-avatar-batman.png', 'default_customer_image_path' => 'bundles/uvdeskcoreframework/images/uv-avatar-ironman.png', 'default_helpdesk_image_path' => 'bundles/uvdeskcoreframework/images/uv-avatar-uvdesk.png', 'max_post_size' => 8388608, 'max_file_uploads' => 20, 'upload_max_filesize' => 2097152, 'user_service' => object(UserService), 'uvdesk_service' => object(UVDeskService), 'ticket_service' => object(TicketService), 'csrf_token_generator' => object(CsrfTokenManager), 'email_service' => object(EmailService), 'uvdesk_extensibles' => object(ExtendableComponentManager), 'uvdesk_core_file_system' => object(FileSystem), 'uvdesk_automations' => object(AutomationService)), array('title' => array(object(__TwigTemplate_52888b8f1b26e6c9a6085f15453384cebcadf7e6832fbc88ce0564edc691bd73), 'block_title'), 'templateCSS' => array(object(__TwigTemplate_52888b8f1b26e6c9a6085f15453384cebcadf7e6832fbc88ce0564edc691bd73), 'block_templateCSS'), 'pageWrapper' => array(object(__TwigTemplate_52888b8f1b26e6c9a6085f15453384cebcadf7e6832fbc88ce0564edc691bd73), 'block_pageWrapper'), 'footer' => array(object(__TwigTemplate_52888b8f1b26e6c9a6085f15453384cebcadf7e6832fbc88ce0564edc691bd73), 'block_footer')))      (vendor/twig/twig/src/Template.php:380)   at Twig\Template->display(array('last_username' => '', 'error' => null))      (vendor/twig/twig/src/Template.php:392)   at Twig\Template->render(array('last_username' => '', 'error' => null), array())      (vendor/twig/twig/src/TemplateWrapper.php:45)   at Twig\TemplateWrapper->render(array('last_username' => '', 'error' => null))      (vendor/twig/twig/src/Environment.php:318)   at Twig\Environment->render('@UVDeskCoreFramework//login.html.twig', array('last_username' => '', 'error' => null))      (vendor/symfony/framework-bundle/Controller/ControllerTrait.php:233)   at Symfony\Bundle\FrameworkBundle\Controller\Controller->render('@UVDeskCoreFramework//login.html.twig', array('last_username' => '', 'error' => null))      (vendor/uvdesk/core-framework/Controller/Authentication.php:23)   at Webkul\UVDesk\CoreFrameworkBundle\Controller\Authentication->login(object(Request))      (vendor/symfony/http-kernel/HttpKernel.php:151)   at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)      (vendor/symfony/http-kernel/HttpKernel.php:68)   at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)      (vendor/symfony/http-kernel/Kernel.php:198)   at Symfony\Component\HttpKernel\Kernel->handle(object(Request))      (public/index.php:25)
--

`

**Comment by papnoisanjeev** [comment]
@fernandogiacomino  
Your database is not fully migrated yet so you are getting this error.

Follow these steps below and  again configure your project.
-> use web installer to to setup your project.
-> If already setup using this(but it was not successfully done) then open your project directory and locate path.
     **src->controller->BaseController.php** open BaseController.php and find **base()**  function.
      comment out line no 43. 
      // return $this->redirectToRoute('helpdesk_knowledgebase', [], 301);  and save file.

Now you will see web installer again.

Fill all the details and configure with new database name. 
Once installation completed uncomment this line.
return $this->redirectToRoute('helpdesk_knowledgebase', [], 301);

If you still face any problem create a support ticket  
**https://support.uvdesk.com/en/customer/create-ticket/** here or mail us at **support@uvdesk.com**.

**Comment by papnoisanjeev** [comment]
@fernandogiacomino 
Is your issue has been resolved?

**Comment by fernandogiacomino** [comment]
Hi @papnoisanjeev, the solution you suggest don't work for me. I am testing version 1.07 and this is the error I get as soon as I start the installation >>>
![imagen](https://user-images.githubusercontent.com/20728688/73759289-80aa0700-474a-11ea-8cba-392c670a61d4.png)

**Comment by papnoisanjeev** [comment]
@fernandogiacomino 

Check below steps and make changes accordingly.

**1.**  Web server might don't have permission to allow overriding of the Apache config on a per-directory basis In **httpd.conf** , Allow Override needs to be set to All for the directory block as mention below:

<Directory /home/users/var/www/htdocs>
Options Indexes FollowSymLinks
**AllowOverride All**
Require all granted

**2.**   If you database password contain some **spacial character**(such as #$%@) then change your password and make it without spacial character.


**3.**   locate **.env** file in your project and make sure **APP_ENV=dev**  when you are doing your setup. 


Restart your server.
And clear your project cache by:
**php bin/console c:c** 

Now try to install your project.


If you still face any problem create a support ticket
https://support.uvdesk.com/en/customer/create-ticket/ here or mail us at support@uvdesk.com.

**Comment by fernandogiacomino** [comment]
Thanks @papnoisanjeev! 
I could finish the installation correctly, by adding "Options Indexes FollowSymLinks" and "Require all granted" in the htaccess file (my hosting did not allow me to use "AllowOverride All").
But then when trying to access the Admin Panel or Knowledgebase the first error returns.

![imagen](https://user-images.githubusercontent.com/20728688/73848731-700b9680-4807-11ea-86ef-8cc698296b58.png)

**Comment by papnoisanjeev** [comment]
@fernandogiacomino 

Check database table **uv_website_knowledgebase** and  **uv_website**. 

If tables exist and data in these table not found means default fixtures not loaded properly.
if tables does't exist it means database migration not completed at all.

**Comment by papnoisanjeev** [comment]
@fernandogiacomino 

Is this resolved?

If you are still facing this problem create a support ticket
https://support.uvdesk.com/en/customer/create-ticket/ here or mail us at support@uvdesk.com.

**Comment by fernandogiacomino** [comment]
@papnoisanjeev, the table **uv_website** is created, columns empty.
**uv_website_knowledgebase** is not created, even without errors in log.

**Comment by papnoisanjeev** [comment]
@fernandogiacomino 

Try once again with this with new database: 
https://github.com/uvdesk/core-framework/issues/278#issuecomment-576109460  

Note:  check it also before setup  https://github.com/uvdesk/core-framework/issues/278#issuecomment-582264462

Create a support ticket we will check why you are facing this problem and try to solve it as soon as possible.
https://support.uvdesk.com/en/customer/create-ticket/ here or mail us at support@uvdesk.com.

**Comment by vaishaliwebkul** [comment]
Hi @fernandogiacomino 
You can reopen the issue if still exist.

**Comment by dksdheeraj** [comment]
> @papnoisanjeev, the table **uv_website** is created, columns with name, data empty.
> **uv_website_knowledgebase** is not created, even without errors in log.

The same issue I am facing. Any solution?

**Comment by glimz** [comment]
I am currently facing the same issue. Who could solve this and how?

**Comment by papnoisanjeev** [comment]
@glimz 

Check [this](https://github.com/uvdesk/community-skeleton/issues/290#issuecomment-661113642) hope it will help !!
