### ISSUE TITLE
Getting exception when redirects customer/agents list from admin panel

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#279]
### Title
 customer/ agent routes render internal server error

### Issue Description

Getting exception when redirects customer/agents list from admin panel if prefix update

Request Url: http://localhost/uvdesk_ecomm/community-skeleton1.0.7/public/en/agent/customers/xhr

### Test Environment

  - version 1.0.7 
 - environment- production in .env

### Steps to reproduce
**It is important to provide a set of clear steps to reproduce this bug.If relevant please include code samples.**

    1. step1- setup fresh uvdesk package
    2. step2- update admin prefix
    3. step3- log in as a member, and go to agent list 
  

### Actual result
 
![Screenshot from 2020-02-01 13-05-58](https://user-images.githubusercontent.com/43210406/73588818-9d003680-44f3-11ea-981d-3be252931d8f.png)

Note: this issue occurs on all routes for customer, agent, email template, saved reply

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul  
We will update **.htaccess** in next release till then you can update it. 

Check here: https://github.com/uvdesk/community-skeleton/issues/232
