### ISSUE TITLE
Getting error during ticket assignment to an agent

### ISSUE THREAD

**Issue by jkjn-tech** [uvdesk/core-framework#283]
**Description**  
I am getting error when assigning newly created ticket to an agent 

**How to reproduce**  
Create new ticket - click and assign ticket to an agent in the right panel.

[uvdesk error msg during Agent assignment.docx](https://github.com/uvdesk/core-framework/files/4170768/uvdesk.error.msg.during.Agent.assignment.docx)

**Comment by vaishaliwebkul** [comment]
Hello jkjn-tech,
   Thanks for notifying this bug

> let us know whether you are able to reproduce the same issue while an assignment of a group or team??

**Comment by papnoisanjeev** [comment]
@jkjn-tech 

Open your project and locate path:
**vendor->uvdesk->core-framework->services->Ticketservice.php**

Open **TicketService.php** and **replace** its code by **current code**.

Get **current code** of TicketService.php from url given below.
https://github.com/uvdesk/core-framework/blob/master/Services/TicketService.php

and replace old code by copy and paste current in your **TicketService.php**


Note: The issue already fixed and will reflect in **Next Release** of **community-skeleton**.(https://github.com/uvdesk/community-skeleton)

**Comment by jkjn-tech** [comment]
Thanks Vaishali & Sanjeev.

Changed TicketService.php code as suggested. Now individual assignment does not throw error but Team and Group assignments throw error (screen shot attaached). 

[uvdesk_Assignment_Group_Team error.docx](https://github.com/uvdesk/core-framework/files/4180069/uvdesk_Assignment_Group_Team.error.docx)

Please help resolve this.

**Comment by papnoisanjeev** [comment]
@jkjn-tech 

Clear your project cache by command:
**php bin/console c:c**

Hard refresh your site and make a try.

**Comment by jkjn-tech** [comment]
Thanks when I try the command "php bin/console c:c" getting memory error.

[Memeory Error- Cache clear.docx](https://github.com/uvdesk/core-framework/files/4190406/Memeory.Error-.Cache.clear.docx)

**Comment by papnoisanjeev** [comment]
@jkjn-tech 

Check here : https://stackoverflow.com/questions/415801/allowed-memory-size-of-33554432-bytes-exhausted-tried-to-allocate-43148176-byte

**Comment by vaishaliwebkul** [comment]
@jkjn-tech 
 Assignment Issue has been fixed, also regarding memory issue please refer https://github.com/uvdesk/community-skeleton/issues/167

Thanks for notifying this bug!
Feel free to reopen this issue! If still not resolved.
