### ISSUE TITLE
No Ticket counts when login as another administrative account

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#285]
# Bug report

### Title
No Ticket counts when login as another administrative account

### Issue Description
No Ticket counts when login as another administrative account

### Preconditions

    1. framework Version- v1.0.8

### Steps to reproduce

    1. step1- Create a user with administrator permission
    2. step2- Login with this user
    3. step3- Go to the ticket list, all tickets visible but tickets counting remains unchanged.

### Expected result
  
 ticket counts should also shown to the other administrative.

### Actual result

![Screenshot (9)](https://user-images.githubusercontent.com/43210406/75318655-e8a6c580-5890-11ea-95af-de66a54f8119.png)

![Screenshot from 2020-02-26 12-00-46](https://user-images.githubusercontent.com/43210406/75318623-d4fb5f00-5890-11ea-89e3-7351b0af34df.png)

**Comment by zaheerabbas1988** [comment]
Is there any fix for this bug? 
Same thing happen when agent logged in. i.e. no count of tickets.

**Comment by vaishaliwebkul** [comment]
@zaheerabbas1988 
   The tickets will show to agent when admin assign the ticket to that agent.
Please assign the ticket to the agent, then reload the agent ticket page again.
