### ISSUE TITLE
File attachment limit exceed

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#29]
Mention the maximum limit (25 MB or below) while attaching file to the ticket, also specify the warning message for the following : 

Currently showing exception when add attachment above 25 MB
![screenshot 73](https://user-images.githubusercontent.com/43210406/50476444-2a6a8080-09ee-11e9-861a-43f68b234b75.png)

![screenshot 74](https://user-images.githubusercontent.com/43210406/50476471-4d953000-09ee-11e9-854f-f0497fc8b761.png)

**Comment by akshaywebkul** [comment]
Although the pull request has been merged, this issue still remains unresolved. Please check the pull request [#219](https://github.com/uvdesk/core-framework/pull/219#issuecomment-541323564) with my updated review.

> A few points we should take into consideration:
> 
>     * We should consider switching to XHR instead of performing a POST request
> 
>     * Maintainers should be able to configure and define the max upload size as per their requirements so it's not a good practice to stick to a specific size limit
> 
>     * Validating file size in the front end should take this limit into consideration as well
> 
>     * We also need to preserve user submitted data if an error occurs instead of just redirecting them to the refer page, all the while ensuring that all errors are displayed correctly, which is why switching to xhr makes much more sense

**Comment by vaishaliwebkul** [comment]
@piyushwebkul 

We need to work more on this issue, as currently, an error message is not user-friendly, its content is too lengthy.
