### ISSUE TITLE
getting exception when apply save reply on ticket

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#292]
**Description**  
getting exception when apply save reply on ticket

**How to reproduce**  
- add a save reply
- apply on ticket 

**Additional context**  
![Screenshot from 2020-03-30 20-45-28](https://user-images.githubusercontent.com/43210406/77929591-7843f780-72c7-11ea-919d-56085376afa7.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 
Please elaborate more to reproduce this issue as normally we have not found this issue.

**Comment by vaishaliwebkul** [comment]
Hi @papnoisanjeev 
Issue has been fixed in master.
