### ISSUE TITLE
translation exception when forwarding ticket thread

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#296]
**Description**  
translation exception when forwarding ticket thread

**How to reproduce**  
- open an any random ticket
- forward a ticket thread

**Additional context**  
![Screenshot (11)](https://user-images.githubusercontent.com/43210406/79740230-f458ba80-831c-11ea-85a5-756788cd1e0e.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 
Issue has been fixed in master  [here](https://github.com/uvdesk/core-framework/commit/6d7656bc85267d9df9c097d78d65620114591fdc).

**Comment by vaishaliwebkul** [comment]
fixed
