### ISSUE TITLE
no tickets 

### ISSUE THREAD

**Issue by laurentiu2** [uvdesk/core-framework#298]
**Description**  
I've set up a new instance of uvdesk (1.0.10) and after all settings, imap ok, smtp ok,  but the emails are not converted into tickets.
There is nothing in the database at uv_thread, uv_tickets

**Additional context**  
![Screenshot 2020-05-09 at 22 11 09](https://user-images.githubusercontent.com/29857699/81482899-effc2f00-9242-11ea-93c9-c5638ed8a01e.png)
Where should I look for any error?

**Comment by papnoisanjeev** [comment]
@laurentiu2 

Most probably your **site_url** is not correct in **uvdesk.yaml** file under **config->packages**.
It should be like  **your_host/project_name/public**

**Comment by laurentiu2** [comment]
Yes, that was it.
And php bin/console c:c did the trick.
Thanks!
