### ISSUE TITLE
helpdesk prefix are resetting when update email settings

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#300]
**Description**  
helpdesk prefix are resetting when update email settings

**How to reproduce**  
- add prefix in uvdesk.yaml

- update email settings

- check uvdesk.yaml prefix will reset to previous value

**Additional context**
    uvdesk_site_path.member_prefix: member
    uvdesk_site_path.knowledgebase_customer_prefix: customer

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 
fixed in master branch you can check it.
https://github.com/uvdesk/core-framework/commit/cd20d236094ae85a9a5b634b2e6f2bf4f0a1090a

Will reflect in next release.
