### ISSUE TITLE
getting exception when drag & drop image on ticket reply editor box

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#303]
**Description**  
getting exception when drag & drop image on ticket reply editor box

**How to reproduce**  

1. go to ticket view page
2. drag and drop the image on editor
3. getting error on network tab

**Additional context**  

![Screenshot from 2020-06-19 10-46-51](https://user-images.githubusercontent.com/43210406/85099143-3bc6ce80-b21a-11ea-9c38-2f3d8a9415b6.png)
![Screenshot from 2020-06-19 10-46-30](https://user-images.githubusercontent.com/43210406/85099149-3d909200-b21a-11ea-9b08-01b64d243a0e.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in master [here](https://github.com/uvdesk/core-framework/commit/3c41006f7d6a939f8123bf87798052ebd003840a) please check.

**Comment by vaishaliwebkul** [comment]
@papnoisanjeev 
thanks it's fixed now
