### ISSUE TITLE
getting exception when update status in ticket set as workflow condition

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#304]
**Description**  
getting exception when update status in ticket set as workflow condition

**How to reproduce**  
- create workflow
( condition as ticket-->update status)
( mail to customer)
(mail to agent)

- go to ticket and update status

**Additional context**  

![Screenshot from 2020-06-29 21-12-28](https://user-images.githubusercontent.com/43210406/86026602-46b90480-ba4d-11ea-9f85-61bcaa449c81.png)

**Comment by papnoisanjeev** [comment]
@vaishali 

Fixed in master [here](https://github.com/uvdesk/core-framework/commit/2d4b1c5dc5bd6a0873c6cc5a7bc987e89bec5dce).

**Comment by vaishaliwebkul** [comment]
@papnoisanjeev 
this issue is fixed but getting too much time to update an status, please look into it.

![Screenshot from 2020-07-17 21-25-02](https://user-images.githubusercontent.com/43210406/87806124-055d8d00-c874-11ea-8b08-ec43a14fca6a.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

As we have checked it is taking 1-3 sec time (which is very normal) for updating the ticket please check again and verify.


![statusUpdate](https://user-images.githubusercontent.com/42460055/90717533-70640e80-e2cd-11ea-9c51-347e86a98a63.PNG)

**Comment by vaishaliwebkul** [comment]
fixed in master
