### ISSUE TITLE
Unable to set environment to production

### ISSUE THREAD

**Issue by pusle** [uvdesk/core-framework#310]
**Description**  
Unable to set environment to `prod`

**How to reproduce**  
I finished the setup of uvdesk version 1.0.12. After editing the .env file and setting `APP_ENV=prod`, and clearing cache, the error occurs.

**Possible Solution**  

**Additional context**  
Error message:
```
$ php bin/console cache:clear

In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:

  The service "security.context_listener.0" has a dependency on a non-existent service "Webkul\UVDesk\ApiBundle\Provi
  ders\ApiCredentials".
```

There is no logged errors in `var/log/prod.log`, in fact the log file is empty. In cache, the only thing cached in prod is:
```
<?php return array (
  0 => 'Symfony\\Bundle\\FrameworkBundle\\Controller\\AbstractController',
);
var/cache/prod/annotations.map (END)
```

Please let me know if I can provide more info.

**Comment by papnoisanjeev** [comment]
@pusle 

Please try to setup your project with Latest release Zip.
https://www.uvdesk.com/en/opensource/  from here.

**Comment by pusle** [comment]
@papnoisanjeev Thanks, that worked

**Comment by inkeyheijden** [comment]
I am getting the same error, even with latest release 1.0.12
Trying to get to prod (in .env file) and want to have api bundle active, but no succes ;(

**Comment by papnoisanjeev** [comment]
@inkeyheijden 

Please try to setup your project with Latest **Released Zip** and  download it from [here](https://www.uvdesk.com/en/opensource/).

**Comment by inkeyheijden** [comment]
@papnoisanjeev Ok! worked! I thought I downloaded the latest release with: _composer create-project uvdesk/community-skeleton helpdesk-project_ but it's different, learning every day ;)

For others; i used 
wget  -P /var/www/uvdesk/ "https://cdn.uvdesk.com/uvdesk/downloads/opensource/uvdesk-community-current-stable.zip"
and unzipped with
unzip uvdesk-community-current-stable.zip
after this I installed the API and worked like a charm in PROD enviroment.

**Comment by papnoisanjeev** [comment]
@inkeyheijden 

> @papnoisanjeev Ok! worked! I thought I downloaded the latest release with: composer create-project uvdesk/community-skeleton helpdesk-project but it's different, learning every day ;)

Yes, unfortunately in last release it was an issue while changing the environment to prod and it is fixed with master branches but will reflect from the next release of project so till then we fixed it for [Latest ZIP](https://www.uvdesk.com/en/opensource/).

Stay tuned with us on Github [repository  ](https://github.com/uvdesk/community-skeleton) for upcoming release and updates.

Also connect with community on [UVdesk Forum](https://forums.uvdesk.com/).
