### ISSUE TITLE
Swift_Message are not "canonical" as used in EmailService and some emails are never sent/recieved (SPAM)

### ISSUE THREAD

**Issue by quazardous** [uvdesk/core-framework#311]
**Description**  
Sometime email are not sent/received through some server (tested with OVH smtp).

**How to reproduce**  
Copy/Paste the main code of EmailService with a mailerId configured with some OVH account.

the main point is `->setBody($content, 'text/html')`

**Possible Solution**  
the official Swiftmail docs says

```php
// Create the message
$message = (new Swift_Message())

  // Give the message a subject
  ->setSubject('Your subject')

  // Set the From address with an associative array
  ->setFrom(['john@doe.com' => 'John Doe'])

  // Set the To addresses with an associative array (setTo/setCc/setBcc)
  ->setTo(['receiver@domain.org', 'other@domain.org' => 'A name'])

  // Give it a body
  ->setBody('Here is the message itself')

  // And optionally an alternative body
  ->addPart('<q>Here is the message itself</q>', 'text/html')

  // Optionally add any attachments
  ->attach(Swift_Attachment::fromPath('my-document.pdf'))
  ;
```

adding Html using this exact function

```php
->setBody($plainContent)
->addPart($content, 'text/html');
```

seams to work at least for me.

But we have to create a plain text content... (most of email clients display the html part) 

**Additional context**

**Comment by papnoisanjeev** [comment]
@quazardous 
 
Added request changes on master branch [here](https://github.com/uvdesk/core-framework/blob/master/Services/EmailService.php#L507) will reflect from next release.
