### ISSUE TITLE
Exception showing when view agent list

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#317]
**Description**  
exception showing when view agent list

**Preconditions** 
Version- master

**How to reproduce**  
step-1 open agent list from the admin panel

**Additional context**  
![Screenshot_37](https://user-images.githubusercontent.com/43210406/95838967-0eb9a100-0d60-11eb-87b5-07f0aecbe09b.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in master.
