### ISSUE TITLE
getting exception when redirect to ticket view page

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#318]
**Description**  
getting exception when redirect to ticket view page

**Precondition**
Version- master

**How to reproduce**  
- open any ticket and then you will find a bug while redirecting to the ticket page

**Additional context**  
![Screenshot_40](https://user-images.githubusercontent.com/43210406/95847407-4c232c00-0d6a-11eb-9a03-777dc8a8e12d.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in master.
