### ISSUE TITLE
exception when creating swiftmailer

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#319]
**Description**  
exception when creating a swift mailer

**Preconditions**
Version- master

**How to reproduce**  
- create swift mailer from the admin end

**Additional context**  
![Screenshot_43](https://user-images.githubusercontent.com/43210406/95854779-09b31c80-0d75-11eb-8114-f43cbb94d35b.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in master.
