### ISSUE TITLE
showing error while save email settings

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#320]
**Description**  
when save email settings, it's showing error on console

**How to reproduce**  
step1- login to admin
step2- search for Email settings and save them

**Additional context**  
![Screenshot_46](https://user-images.githubusercontent.com/43210406/95856924-70860500-0d78-11eb-8cfe-007b62ff0c9f.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in master.
