### ISSUE TITLE
display flash message when save branding theme

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#321]
**Description**  
display flash message when save branding theme

**How to reproduce**  
>> go to the admin panel
>> search for branding
>> now save (flash message should appear)
 
**Additional context**  
![Screenshot_56](https://user-images.githubusercontent.com/43210406/96099511-f200a300-0ef0-11eb-9e97-cd1bbaed747e.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

fixed in master.

**Comment by vaishaliwebkul** [comment]
fixed https://prnt.sc/v10uis
