### ISSUE TITLE
error on console when add new email template

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#322]
**Description**  
error on console when add new email template

**Precondition**
Version- master

**How to reproduce**  
-> click on add email template button

**Additional context**  
![Screenshot_57](https://user-images.githubusercontent.com/43210406/96109436-41989c00-0efc-11eb-8c78-fe540704a2e7.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in master.
