### ISSUE TITLE
getting exception when submitting a reply to ticket

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#323]
**Description**  
getting exception when submitting a reply to ticket

**Precondition**
Version- master

**How to reproduce**  
1.  open a ticket
2.  submit a reply to the ticket

**Additional context**  
![Screenshot_58](https://user-images.githubusercontent.com/43210406/96126402-bde9aa00-0f11-11eb-9329-15848747f25d.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 
fixed in master.
