### ISSUE TITLE
getting error when save agent profile

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#325]
**Description**  
getting error when save agent profile

**Precondition**

Version- master

**How to reproduce**  
- login with agent panel or edit profile then save

**Additional context**  
![Screenshot_62](https://user-images.githubusercontent.com/43210406/96236807-1d9b9000-0fba-11eb-9ee3-007956446fa4.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed with master branch.
