### ISSUE TITLE
ticket quick view icon is not working

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#326]
**Description**  
ticket quick view icon is not working

**Precondition**
Version- master

**How to reproduce**  
>> go to the ticket list
>> click on quick view icon

**Additional context**  
![Screenshot_63](https://user-images.githubusercontent.com/43210406/96245689-35c4dc80-0fc5-11eb-93e7-36fe3b354974.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in master.
