### ISSUE TITLE
customer profile image is broken in filter

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#327]
**Description**  
customer profile image is broken in filter

**Precondition**
Version-  master

**How to reproduce**  
-> ticket list filter view
-> filter based on customer(make sure customer should have profile image)

**Additional context**  
![Screenshot_64](https://user-images.githubusercontent.com/43210406/96251322-e505b180-0fcd-11eb-84d2-2c745e8a8447.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in master [here](https://github.com/uvdesk/core-framework/commit/fd7e5dcea83330cb29a3470aefdf1ee29ffeac76).

**Comment by vaishaliwebkul** [comment]
fixed
