### ISSUE TITLE
Not able to remove assigned group/team from saved replies

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#330]
**Description**  
Not able to remove assigned group/team from saved replies

**Precondition**
Version- master

**How to reproduce**  
1. create saved reply by selecting any group and team and save
2. unselect the group/team again & save
3. you will see the group/team will not remove

**Additional context**  
![Screenshot_69](https://user-images.githubusercontent.com/43210406/96337289-9f1b1d00-10a3-11eb-8ff6-612ff46afacd.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

**Group** and **Teams** **remove** issue has been fixed [here](https://github.com/uvdesk/core-framework/commit/fd625edefd54175080d5a6e049d9bb366aba8709).

Fixed in master and will reflect in next release.

**Comment by vaishaliwebkul** [comment]
@papnoisanjeev 
getting error when add/save saved replies with latest core-framework
![Screenshot_247](https://user-images.githubusercontent.com/43210406/106909467-56f13a80-6726-11eb-9e85-9721ef2037a5.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Updated [here ](https://github.com/uvdesk/core-framework/commit/48556eb096cb864b3b07b1ef73b2c30d13a94a7e)in master please verify.
