### ISSUE TITLE
unnecessary privilege added

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#331]
**Description**  
Remove the privilege which doesn't have any use in this platform

**How to reproduce**  
step-1 go to privileges
step-2 add new-> under the 'agent privilege'-> remove "can kick other ticket user"

**Additional context**  
It should be removed
![Screenshot_68](https://user-images.githubusercontent.com/43210406/96337813-611ff800-10a7-11eb-81a4-5387debb6290.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Removed unnecessary privileges removed. Fixed in master branch.
