### ISSUE TITLE
getting exception when agent update customer profile

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#332]
**Description**  
getting exception when agent update customer profile

**Precodition**
Version- master

**How to reproduce**  
- login as admin
- edit customer and upload profile

**Additional context**  
![Screenshot_75](https://user-images.githubusercontent.com/43210406/96441595-6b690000-1227-11eb-84a7-fe0e6e2f80bc.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed with master.
