### ISSUE TITLE
Email validation failure

### ISSUE THREAD

**Issue by bessone** [uvdesk/core-framework#334]
**Description**  
Javascript Email validation uses a regex that doesn't accept the latest TLDs, such as .support. The TLD limit is 4 characters

**How to reproduce**  
Create a new SwitfMailer and use an email address with a recent TLD longer than 4 characters, e.g. helpdesk@example.support

**Possible Solution**  
Replace the regex with a better one

**Comment by papnoisanjeev** [comment]
@bessone 

Pull request is already merged.
So closing this issue.
