### ISSUE TITLE
Asking for ability to set color of all text on homepage. 

### ISSUE THREAD

**Issue by WaffleThief123** [uvdesk/core-framework#337]
**Description**  

We are looking for the ability to change the color of the text on the homepage, it currently is set to a grey, and we can't find any way to change it that doesn't involve "breaking" the codebase that would be changed with a new release. 

Currently it looks like this
![image](https://user-images.githubusercontent.com/26676249/105948067-25d68300-601f-11eb-950f-653c631107d2.png)
 and we would like to be able to modify the text color on this menu.
 
 
![image](https://user-images.githubusercontent.com/26676249/105948138-43a3e800-601f-11eb-956f-713c0c4b0bac.png)

**Example**  
Possibly adding an option to the Branding Menu for this
![image](https://user-images.githubusercontent.com/26676249/105948311-94b3dc00-601f-11eb-86c6-eb0a56973852.png)

**Comment by papnoisanjeev** [comment]
@WaffleThief123 

Currently for **text** there is no option to change its color form web.
But if you need any specific color for the same you can add a style for the same.

locate path in your project:
**vendor/uvdesk/support-center-bundle/Resources/views/Themes**  you will see different theme templates here.
You need to make changes into these files.

https://github.com/uvdesk/support-center-bundle/tree/master/Resources/views/Themes

Example:
As we can see your selected layout is  **Masonry view** so you need to make changes in **masonryView.html.twig**
- Like for **heading** if you need to a **Red color:**

`<h1 style="color: red" class="uv-text-center">{{ "Browse via Folders"|trans}}</h1>`

Check this:  https://prnt.sc/xp1xzh

- For paragraph:
If you need yellow color then:

`<p style="color:yellow" class="uv-text-center uv-fixed-width">{{ "Looking for something that is queried generally? Choose a relevant folder from below to explore possible solutions"|trans}}</p>`

Check this: https://prnt.sc/xp2e6d

**Comment by WaffleThief123** [comment]
Awesome, Thank you!
