### ISSUE TITLE
EmailService: add text/plain version of the email content

### ISSUE THREAD

**Issue by fdyckhoff** [uvdesk/core-framework#338]
**Description**  

Sending emails without text/plain version of the email might add to the risk that an email is considered as spam by email providers. Please add a plaintext version of the email content when generating the Swiftmailer message in the EmailService class

https://github.com/uvdesk/core-framework/blob/master/Services/EmailService.php#L506

**Example**  

`$message->addPart(strip_tags($content), 'text/plain');`

but it might be better to use a converter like https://github.com/soundasleep/html2text or https://packagist.org/packages/html2text/html2text instead of strip_tags.

**Comment by papnoisanjeev** [comment]
@fdyckhoff 

Updated [here](https://github.com/uvdesk/core-framework/blob/master/Services/EmailService.php#L507) in master branch.
