### ISSUE TITLE
assign ticket are not visible to agent in my ticket section

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#340]
**Description**  
When Agent check the assigned ticket at 'My ticket' section are not visible but showing valid count

![Screenshot_300](https://user-images.githubusercontent.com/43210406/108227335-cd009300-7163-11eb-9f0c-fa504060fb6d.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed [here ](https://github.com/uvdesk/core-framework/commit/fe069ac9698f9c7909888bff3fcb8551c4e48091) please verify with master branch.

**Comment by vaishaliwebkul** [comment]
fixed now
