### ISSUE TITLE
saved reply is getting removed from the agent panel

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#343]
**Description**  

- create saved reply by admin then assign this to a user group
- login with agent exist in the same group
- saved reply and edit & saved 
- Now the saved reply will get removed

![Screenshot_305](https://user-images.githubusercontent.com/43210406/108832803-04eb5880-75f2-11eb-8461-5c804ec85bb1.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed in master [here](https://github.com/uvdesk/core-framework/commit/031a2c7d6b7383f12a16d468b7733dac01a885b8).

**Comment by vaishaliwebkul** [comment]
fixed
