### ISSUE TITLE
duplicate customer routes are visible on search at admin panel

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#349]
**Description**  
duplicate customer routes are visible on search at admin panel

![Screenshot_308](https://user-images.githubusercontent.com/43210406/109156840-584adb80-7797-11eb-830b-b8a03ba63597.png)

![Screenshot_309](https://user-images.githubusercontent.com/43210406/109157216-becff980-7797-11eb-8952-a248fd1f5d0b.png)

![Screenshot_310](https://user-images.githubusercontent.com/43210406/109157315-e0c97c00-7797-11eb-82ab-3eee9d94cc0e.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed here.
https://github.com/uvdesk/core-framework/commit/facc5cf8309da2cce9717f1d405e25636224cc7f
https://github.com/uvdesk/support-center-bundle/commit/c4d97ef5bd68689b0fcba119506087bd89bf99f6

**Comment by vaishaliwebkul** [comment]
fixed
