### ISSUE TITLE
No result option is active to added in the tags and labels fields with ticket

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#35]
### **search keyword(by entering starting key of label and tags) in label and tags fields then **no result found** option is also active to be added in the tags and labels with ticket**

![screenshot 82](https://user-images.githubusercontent.com/43210406/50512798-04121700-0aba-11e9-9a27-947811b5a320.png)

**Comment by papnoisanjeev** [comment]
fixed.
