### ISSUE TITLE
Update jQuery to update to 3.6.0

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/core-framework#352]
jQuery need to be updated but issue with the latest jQuery version.
https://github.com/uvdesk/core-framework/pull/351
https://github.com/uvdesk/support-center-bundle/pull/127

jQuery need to be updated:
https://blog.jquery.com/2021/03/02/jquery-3-6-0-released/

**Comment by PeopleInside** [comment]
@papnoisanjeev I hope, if you will release a [new version soon](https://forums.uvdesk.com/topic/1913/email-to-agent-when-customer-reply-to-ticket/8), this will be fixed.

I cannot help you as I followed instruction you told me in the past to update jQuery but once done the uvdesk web interface is broken so, you need test and resolve this.

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Updated jQuery version from **2.x** it to **3.x**.

**Comment by PeopleInside** [comment]
This is not resolved. JQuery was not updated to the latest version.

**Comment by PeopleInside** [comment]
The UVdesk code need to be updated because is obsolete.

Updating jQuery from 2.x to 3.x is good but not enough because you just updated jQuery to a more recent version but not to the latest stable version.

I would be happy to update in my install but as updating create issue because maybe some code in PHP are deprecated, cannot update.

Closing this issue is not correct as the issue is not resolved.
