### ISSUE TITLE
Last reply option is missing Asset Visibility

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#356]
**Description**  
Last reply option is missing Asset Visibility

![Screenshot_332](https://user-images.githubusercontent.com/43210406/113020504-49918300-91a0-11eb-8beb-817af4105709.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

**Last reply** field is a permanent header, not optionally added for ticket list.
