### ISSUE TITLE
collaborator reply are not being added into ticket

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#358]
**Description**  
When the collaborator added a reply on a ticket then new ticket has been created all the time instead of adding reply in same ticket

**How to reproduce**  
Add a reply of ticket by a collaborator from email

![Screenshot_341](https://user-images.githubusercontent.com/43210406/113280605-21ba3080-9302-11eb-930d-9a7a4f5ac861.png)

![Screenshot_340](https://user-images.githubusercontent.com/43210406/113280594-1cf57c80-9302-11eb-968b-c19d4723a5a7.png)

**Comment by Komal-sharma-2712** [comment]
I am also getting the same issue

**Comment by Sanjaybhattwebkul** [comment]
resolve and update [here](https://github.com/Sanjaybhattwebkul/core-framework/commit/306dc157268ec6175bbbbaf691a7163e6ce68253)
