### ISSUE TITLE
collaborator reply to ticket action's are not working

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#359]
**Description**  
collaborator reply to ticket actions are not working

>> create workflow
>> ticket -> collaborator added reply
>> mail to customer

The action's are not working when the collaborator added a reply

![Screenshot_311](https://user-images.githubusercontent.com/43210406/109163229-1b82e280-779f-11eb-89bb-5254fbf7b4eb.png)

**Comment by Sanjaybhattwebkul** [comment]
@vaishaliwebkul   we fixed it in master please check
