### ISSUE TITLE
Update jQuery to update to 3.6.0

### ISSUE THREAD

**Issue by PeopleInside** [uvdesk/core-framework#361]
jQuery need to be updated but issue with the latest jQuery version.
https://github.com/uvdesk/core-framework/pull/351
https://github.com/uvdesk/support-center-bundle/pull/127

jQuery need to be updated:
https://blog.jquery.com/2021/03/02/jquery-3-6-0-released/

https://github.com/uvdesk/core-framework/issues/352

The UVdesk code need to be updated because is obsolete.

Updating jQuery from 2.x to 3.x is good but not enough because you just updated jQuery to a more recent version but not to the latest stable version.

I would be happy to update in my install but as updating create issue because maybe some code in PHP are deprecated, cannot update.

Please do not close the issue if you has not updated jQuery to the latest version available 3.6.0
https://jquery.com/

**Comment by papnoisanjeev** [comment]
@PeopleInside 

As we have tested the project with **3.5** so everything was running good.
Also we are doing **next release of project** today itself for the project so at this time we can not take a risk if something will be broken by using 3.6.

Don't worry we will add all latest version in next release with proper test.

**Comment by PeopleInside** [comment]
Great but don't close this issue if is not resolved.

**Comment by PeopleInside** [comment]
@papnoisanjeev as you never support composer 2 I need a solution from you to update to the latest version as soon you released because I need fix some bug like the recaptcha not integrated in the UI that can compromise UVdesk if i save email settings.

**Comment by PeopleInside** [comment]
For now there is no security issue as I know but if this will come in jQuery remember I will be unable to update as UVdesk is not supporting the latest jQuery version... so I will have a very strong issue. For now no security issue so for me is not a problem have not the latest version but if will be and jQuery will release a security fix I will be unable to apply, this is why I'm scared :D in the past this happen so.. is not so just a dream :)

**Comment by papnoisanjeev** [comment]
@PeopleInside 

Will do all the remaining things after this release.
But as there are many updates which need to be release first to short out many issues which users were facing.

**Comment by PeopleInside** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/5006150/115959273-b4b64700-a50b-11eb-96f1-26b5a9b8aea4.jpg)
