### ISSUE TITLE
An exception has been thrown during the rendering of a template ("Class "1\BaseController" does not exist in C:\Program Files\Xampp\htdocs\uvdesk-community-v1.0.13\config/routes\../../src/Controller/ (which is being imported from "C:\Program Files\Xampp\htdocs\uvdesk-community-v1.0.13\config/routes/annotations.yaml"). Make sure annotations are installed and enabled.").

### ISSUE THREAD

**Issue by Axiser0** [uvdesk/core-framework#362]
An exception has been thrown during the rendering of a template ("Class "1\BaseController" does not exist in C:\Program Files\Xampp\htdocs\uvdesk-community-v1.0.13\config/routes\../../src/Controller/ (which is being imported from "C:\Program Files\Xampp\htdocs\uvdesk-community-v1.0.13\config/routes/annotations.yaml"). Make sure annotations are installed and enabled.").
--
in trace.html.twig line 13

**Comment by Axiser0** [comment]
![Uploading Capture.PNG…]()

**Comment by papnoisanjeev** [comment]
@Axiser0 

Please let us know when you are facing this issue.

@vaishaliwebkul  Please verify.

**Comment by vaishaliwebkul** [comment]
@Axiser0 
Kindly clear the project cache **php bin/console c:c** then check if the same error still error persists.

**Comment by Axiser0** [comment]
@papnoisanjeev  when am installing it

**Comment by Axiser0** [comment]
@vaishaliwebkul didnt work

**Comment by vaishaliwebkul** [comment]
@Axiser0 
Are you still facing this issue or it has been resolved?

**Comment by vaishaliwebkul** [comment]
@Axiser0 
I hope the issue has been resolved, so closing this right now.
