### ISSUE TITLE
add privilege to show agent ticket activity

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#364]
**Description**  
Currently, at the agent panel, activity icon is visible but there is no option to manage "Agent activity" by privilege.

**How to reproduce**  

- Go to agent panel
- click on report section

**Additional context**  
Add privilege "Can view agent ticket activities" 
![Screenshot_356](https://user-images.githubusercontent.com/43210406/116780952-5bb35980-aa9d-11eb-8d98-c1c9425e8cf8.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 
we have added privilege for the same please verify.

**Comment by vaishaliwebkul** [comment]
@papnoisanjeev 
bug is still not fixed when agent don't have privilege then report icon still exists in menu https://prnt.sc/132yign

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

We will add more section under reports so according to access only allowed sections will be visible to agent.
So navigation bar will be visible for this.
