### ISSUE TITLE
exception when agent view activity section

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#369]
![Screenshot_369](https://user-images.githubusercontent.com/43210406/118673693-d6f36a00-b816-11eb-8e6a-f698151cf458.png)

**Comment by vipin-shrivastava** [comment]
@vaishaliwebkul 

I think this issue has already fixed.
I checked it but I didn't found.
https://prnt.sc/13pkp20

**Comment by vaishaliwebkul** [comment]
fixed
