### ISSUE TITLE
Creating a new agent without activating creates zombie agent

### ISSUE THREAD

**Issue by wmertens** [uvdesk/core-framework#370]
When you create a new agent but you forget to click the "user is enabled" checkbox, they will show as active but they won't be active.

The workaround is to disable them and then enable them again, then they can log in.

**Comment by vaishaliwebkul** [comment]
@wmertens 
Thanks for reporting the bug, we will fix it soon.

**Comment by papnoisanjeev** [comment]
@wmertens @vaishaliwebkul 

Issue has been fixed [here](https://github.com/uvdesk/core-framework/commit/3441006b2beffcd4d72f59a55eee5c1dc4f4f232#diff-66f7ac5c9b2e0f4a4d0e58904ccf5feedf686cd1171ab894f99193bbca3735ceR187).

You can replace this line in **UserService.php** at line 187 and will work as expected.

**Comment by vaishaliwebkul** [comment]
@wmertens 
 I have verified the changes made and it's fixed now.
so closing this issue.
