### ISSUE TITLE
getting exception when edit agent profile

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#371]
**Description**  
https://github.com/uvdesk/core-framework/tree/custom_field

**How to reproduce**  
Admin-> edit agent profile

![Screenshot_376](https://user-images.githubusercontent.com/43210406/120326651-93b0f500-c306-11eb-807e-6910d7a07eb1.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed it in respective branch [here ](https://github.com/uvdesk/core-framework/commit/0dfbc14c5511cec5d5496c8202da8e4c04d6bad7)you can check.

**Comment by vaishaliwebkul** [comment]
@papnoisanjeev 
It's fixed now.
