### ISSUE TITLE
Getting 404 on ticket view at agent panel if group is not added in ticket

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#372]
**Description**  
Getting 404 on ticket view at agent panel if group is not added in ticket

**How to reproduce**  

- Add Agent-> assign group[default] -> ticket access(group access)
- Assign ticket to agent but don't assign group to that ticket
- Go to agent panel
- Ticket is visible here but when view ticket getting 404.

**Additional context**  
![Screenshot_377](https://user-images.githubusercontent.com/43210406/120343093-0aa1ba00-c316-11eb-92c9-0dcfcfbb1200.png)
![Screenshot_378](https://user-images.githubusercontent.com/43210406/120343103-0c6b7d80-c316-11eb-8b2f-696a35e885d9.png)
![Screenshot_379](https://user-images.githubusercontent.com/43210406/120343108-0d041400-c316-11eb-9f88-490b8b3d865b.png)

**Comment by vipin-shrivastava** [comment]
@vaishaliwebkul 

As I checked this issue , I didn't found it.
I also added screenshot here :
![Screenshot_2](https://user-images.githubusercontent.com/58874186/120446491-3d47c300-c3a7-11eb-8cb4-c25654bff4f3.png)
![Screenshot_3](https://user-images.githubusercontent.com/58874186/120446512-43d63a80-c3a7-11eb-9a69-7e909e228cd1.png)
![Screenshot_5](https://user-images.githubusercontent.com/58874186/120446536-49cc1b80-c3a7-11eb-8ec4-121984042012.png)

**Comment by Komal-sharma-2712** [comment]
I am getting Same error again showing :

When click ticket for view: 
![agent-side-ticketlist after clicking ticket page not found](https://user-images.githubusercontent.com/63539748/130433658-67c4a6a9-acc6-4d3f-bd1c-43c305d5e783.png)

When go to agent panel:
![agent-side-ticketlist not view bcoz not defined group option2-agent dash](https://user-images.githubusercontent.com/63539748/130433682-962fe3df-b3e9-4bce-8768-0c185b04ad03.png)

when go to admin panel:
![agent-side-ticketlist not view bcoz not defined group option](https://user-images.githubusercontent.com/63539748/130433671-836458ab-895e-4ca1-8cdf-84d6567d9860.png)

When go to inner ticket view from admin panel here are not assigned group: 
![agent-side-ticketlist not view bcoz not defined group option1](https://user-images.githubusercontent.com/63539748/130433676-10e5852a-b768-40fa-966a-b74a077fdaf1.png)
