### ISSUE TITLE
admin name is not coming in agent list drop down

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#373]
**Description**  
admin name is not coming in agent list drop down

**How to reproduce**  
![Screenshot_381](https://user-images.githubusercontent.com/43210406/121529109-b3889d00-ca19-11eb-8bc1-2e0d57185137.png)
![Screenshot_382](https://user-images.githubusercontent.com/43210406/121529120-b71c2400-ca19-11eb-8102-ad17ef44c9c5.png)

**Comment by vipin-shrivastava** [comment]
![Screenshot_14](https://user-images.githubusercontent.com/58874186/121565987-ab8d2500-ca3a-11eb-9b4d-8bd0d04ae8b0.png)
![Screenshot_13](https://user-images.githubusercontent.com/58874186/121565996-ae881580-ca3a-11eb-9fb5-d6d749f20ef8.png)

@vaishaliwebkul 
I didn't find the any issue in team->user field.
