### ISSUE TITLE
{%ticket.customerEmail%} placeholder is not working with saved replies when apply on ticket

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#374]
**Description**  

{%ticket.customerEmail%} placeholder is not working with saved replies when apply to ticket

![Screenshot_383](https://user-images.githubusercontent.com/43210406/121536667-e5e9c880-ca20-11eb-9574-aca8f00e94d7.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 
 Fixed [here](https://github.com/uvdesk/core-framework/commit/ecbb4db49c5c09eca94e5d9c4d5193d7582dd398).
