### ISSUE TITLE
Role is not translated in the Agents listing screen

### ISSUE THREAD

**Issue by akhileshkcoder** [uvdesk/core-framework#375]
I have customized UVdesk and have changed the name of 'Agent' to 'Customer Support'.  I have done the changes in the language file inside the translations folder. The name is successfully changed everywhere except for the role name in the agents' listing screen.  I have found in the code that the translator is not used for the role. How can I use the translator in the code?

![image](https://user-images.githubusercontent.com/62323833/122428511-94f14b80-cfaf-11eb-8f3b-6dd7d02e14ac.png)

The agents are listed from the function 'getAllAgents()' in the file uvdesk-community\vendor\uvdesk\core-framework\Repository\UserRepository.php  I want to use the translator in that file. I am not familiar with Symfony. Please help.

![image](https://user-images.githubusercontent.com/62323833/122429115-252f9080-cfb0-11eb-90bc-f005e4df132e.png)

**Comment by papnoisanjeev** [comment]
@akhileshkcoder 

You can change these entry directly from database table **uv_support_role** for your desired language.

https://tinyurl.com/yzma3jrp

**Comment by akhileshkcoder** [comment]
@papnoisanjeev  Thank you. But in that case, in the future, if I want multiple language support it will be a problem.

**Comment by papnoisanjeev** [comment]
@akhileshkcoder 

Basically translation is done for static data only not for the data which is coming from database.
As we can add or update that data as per our language.

Still as role have table have fixed data so will try to translate it using code.

**Comment by Sanjaybhattwebkul** [comment]
@akhileshkcoder   We have fix this issue in master 

 **Please [check](https://github.com/uvdesk/core-framework/commit/e545b78f0d96cf29be2dc6f625ef95189f378443#diff-b70086cc7666b63d4b88349ce5704b44e26c3aa620760d0f334ea144c9f927ccL117-R126)**

**Comment by akhileshkcoder** [comment]
okay. Thank you
