### ISSUE TITLE
getting exception when add custom javascript/css in branding section

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#377]
**Description**  
getting exception when adding custom javascript/CSS in branding section

**How to reproduce**  
Go to admin panel -> Branding -> Advanced
Add custom javascript code and click on save

**Additional context**  
![Screenshot_2](https://user-images.githubusercontent.com/43210406/123780860-40c06280-d8f1-11eb-9efa-ce59991b3e20.png)

**Comment by Sanjaybhattwebkul** [comment]
**i have followed all the given steps but no issue found . we can add custom css and js code without any issue**
 Please find the screenshots below
![Branding-issue](https://user-images.githubusercontent.com/86394952/126450485-2ac252f8-9f8d-4f8c-ac0c-573c8234d76a.PNG)

**Comment by vaishaliwebkul** [comment]
fixed now
