### ISSUE TITLE
Add additional field for agent and include that field in search

### ISSUE THREAD

**Issue by akhileshkcoder** [uvdesk/core-framework#378]
I want to add an additional field 'place' when creating an agent and use that field while searching an agent in the ticket listing screen. I have gone through the code and was able to understand how to insert the new field. But the problem is I can't understand how the search functionality is done. 

![image](https://user-images.githubusercontent.com/62323833/123810740-46797080-d910-11eb-8e46-944a605d22db.png)

It's a `<ul>` list and the `<li>` tag is hidden based on the search, I couldn't find the script that does this functionality.  Please help me find the code that does this functionality.

**Comment by papnoisanjeev** [comment]
@akhileshkcoder 

You need to add your new field in database table using entity changes.

then open **UserRepository.php** and add your field.

You can add your new field [here](https://github.com/uvdesk/core-framework/blob/master/Repository/UserRepository.php#L39).

**Comment by akhileshkcoder** [comment]
@papnoisanjeev Thanks. But there is no request going in the browser's network. So I think it is searching within the available HTML list using javascript.

**Comment by papnoisanjeev** [comment]
@akhileshkcoder 

https://github.com/uvdesk/core-framework/blob/ffbb16c45109d06d3012e937e8aeded10935db5f/Services/UserService.php#L260

Add more conditions here.

**Comment by akhileshkcoder** [comment]
@papnoisanjeev 

No. I tried, it doesn't work. As I said the search is happening on the client-side.

**Comment by akhileshkcoder** [comment]
@papnoisanjeev I found it. It is in dropdown.js script.

**Comment by vipin-shrivastava** [comment]
@akhileshkcoder 

As I checked in dropdown.js it only works for sorting agents from `<li>` on basis of the given input name.
`<li>` is for list of agents.
We had fetched all agents from  [user service](https://github.com/uvdesk/core-framework/blob/ffbb16c45109d06d3012e937e8aeded10935db5f/Resources/views/ticket.html.twig#L438) on loading the page.

If you want to search agents on the basis of their mobile number. first, you have to add it to `<li>` then after you can search.

**Comment by akhileshkcoder** [comment]
This is the code. 

![image](https://user-images.githubusercontent.com/62323833/124071583-31f6be80-da5d-11eb-8e47-ed5245309f88.png)

**Comment by vipin-shrivastava** [comment]
@akhileshkcoder 
Yes, you can changes here for sorting on the basis of your requirement also don't forget to add the following parameter in `<li>`.

I hope this will help you . if not please let me know

**Comment by akhileshkcoder** [comment]
@vipin-shrivastava 

You need to add your new field in database table using entity changes. // How to do this? Please help.

**Comment by akhileshkcoder** [comment]
@papnoisanjeev @vipin-shrivastava Thanks. I was able to do the changes.

**Comment by papnoisanjeev** [comment]
@akhileshkcoder 

Glad to know that.
Also you can contribute for this opensource project by creating a pull request if you are adding some feature.
