### ISSUE TITLE
Characters such as ö,ü or ä not allowed in agent names

### ISSUE THREAD

**Issue by chrizdee** [uvdesk/core-framework#379]
Names in German are often written with characters like ö,ü or ä. Currently, these characters cannot be used with agent names and this error message appears:

`This field must have characters only`

**Comment by vipin-shrivastava** [comment]
@chrizdee 

Can you please share the screenshot so that we can understand the issue ?

**Comment by chrizdee** [comment]
Thank you for you fast response.

**Here an example:**
![special-chars](https://user-images.githubusercontent.com/4388030/124267441-8ae75500-db38-11eb-85fb-26b31621d086.png)

**Comment by vipin-shrivastava** [comment]
@chrizdee 
We have added regex validation in the first & last names not to allow special characters & numbers.

If you want to allow some special characters like ö,ü or ä. 
you have to update the given regex in the following files : 
updated regex :  `/^[A-Za-z\x7f-\xff][A-Za-z\x7f-\xff]*[\sA-Za-z\x7f-\xff]*$/
`
1. your_project_name/vendor/uvdesk/core-framework/Resources/views/Agents/createSupportAgent.html.twig
   Line no. 351,361
2. your_project_name/vendor/uvdesk/core-framework/Resources/views/Agents/updateSupportAgent.html.twig
   Line no. 399,408
3. your_project_name/vendor/uvdesk/core-framework/Resources/views/Customers/createSupportCustomer.html.twig
   Line no. 136,145
4. your_project_name/vendor/uvdesk/core-framework/Resources/views/Customers/updateSupportCustomer.html.twig
   Line no. 139,148

After the changes you are able to take special charater  in your first & last name.

If you still facing some issues . Please let me know.

**Comment by chrizdee** [comment]
@vipin-shrivastava 

Works perfect!
Thank you for your super fast support 👍
