### ISSUE TITLE
Create ticket by attaching media in a message body but not receive attached media in ticket

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#38]
### Customer Create ticket by the following content , media ,tables by mail : 

![screenshot 8](https://user-images.githubusercontent.com/43210406/50534039-455b0300-0b5c-11e9-984b-8c22eb53ba73.png)
 
### At ticket detail only text content receives : 
![screenshot 86](https://user-images.githubusercontent.com/43210406/50534088-227d1e80-0b5d-11e9-9545-306c2e8e200f.png)

**Comment by vaishaliwebkul** [comment]
When customer mail by attaching image using **Thunderbird** mail -- 
![screenshot 83](https://user-images.githubusercontent.com/43210406/51663002-89b2b500-1fdb-11e9-92b7-872914646059.png)

**Comment by papnoisanjeev** [comment]
fixed
