### ISSUE TITLE
getting exception when filter kudos based on customer group

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#383]
![Screenshot_21](https://user-images.githubusercontent.com/43210406/126736319-e81ca5d6-8e74-4079-ad01-578445508956.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed [here](https://github.com/uvdesk/core-framework/commit/edaa916785cde936abb011fb463f24736d6955bc).
