### ISSUE TITLE
broken image on kudos customer filter 

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#384]
**Description**  
![Screenshot_22](https://user-images.githubusercontent.com/43210406/126736883-1566ea37-6c04-46af-8f1d-d82084f4cd74.png)

**Comment by papnoisanjeev** [comment]
@vaishaliwebkul 

Fixed [here](https://github.com/uvdesk/core-framework/commit/275b333319aee34dc856ca7d6cbed6251a9960e0).
