### ISSUE TITLE
customer image should be visible along with customer name in kudos grid

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#385]
**Description**  
customer image should be visible along with customer name in kudos grid

![Screenshot_25](https://user-images.githubusercontent.com/43210406/126737831-6de490bd-f1c6-4602-8182-37a71b1a55b4.png)

**Comment by vipin-shrivastava** [comment]
@vaishaliwebkul

Fixed [here](https://github.com/uvdesk/core-framework/commit/09b4c3b1d643ae1f0dc9b817ff757884300e68c2).
