### ISSUE TITLE
Collaborator name is coming wrong on ticket thread at agent ticket view

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#386]
**Description**  
Collaborator is coming on a ticket using any customer and collaborator reply on the ticket but not show her name in reply.

**How to reproduce**  
Step 1. Add a Collaborator using Customer.
Step 2. Collaborator gives the Customer created email and changes the password.
Step 3. Then, the collaborator login and give a reply to the ticket.
Step 4. Admin and Agent Panel wrong name showing.

**Additional context**  
When the collaborator added a reply on a ticket then:

![Screenshot](https://user-images.githubusercontent.com/63539748/126997052-e671318a-a612-490c-99f0-52c46954e0c5.png)

When the reply on the agent and admin panel showing the wrong name:

![Screenshot1](https://user-images.githubusercontent.com/63539748/126997383-3ec9524e-c176-4419-9788-0bf91cf6ee1c.png)

**Comment by Sanjaybhattwebkul** [comment]
resolve and update [here](https://github.com/Sanjaybhattwebkul/core-framework/commit/7ed001b62d7fae3e3344ac401f42b002dcc49577).

**Comment by vaishaliwebkul** [comment]
@Sanjaybhattwebkul 
open the PR for this fix.

**Comment by Sanjaybhattwebkul** [comment]
@Komal-sharma-2712  we fixed this issue in master please check
