### ISSUE TITLE
Collaborator on email is  coming wrong format

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#387]
**Description**  
when the agent reply on the collaborator ticket thread so email format is not properly showing to the collaborator.

**How to reproduce**  
Step 1. Login from the agent side.
Step 2. Then reply on added collaborator ticket thread.
Step 3. Go to collaborator email so the email format is not properly showing.

**Additional context**  
When the agent added a reply on a Collaborator ticket thread then:

![Screenshot](https://user-images.githubusercontent.com/63539748/127136357-a26b215a-61ca-4e54-807b-d3d20c36f183.png)

![Screenshot1](https://user-images.githubusercontent.com/63539748/127136853-28a8587e-19a5-405d-b829-69e55d1bc17e.png)

when collaborator checks mail:

![agent reply on collaborator](https://user-images.githubusercontent.com/63539748/127136433-c5a59d4b-89e7-4b99-897d-a7fe634f2887.png)

**Comment by Sanjaybhattwebkul** [comment]
resolve and update [here](https://github.com/Sanjaybhattwebkul/core-framework/commit/41e37e9e56f24ca6b623bbc7797ef7e5824fea0e).

**Comment by vaishaliwebkul** [comment]
@Sanjaybhattwebkul 
Open the PR for the same fix.

**Comment by Sanjaybhattwebkul** [comment]
@vaishaliwebkul   I will do  it soon

**Comment by Sanjaybhattwebkul** [comment]
update [here](https://github.com/uvdesk/core-framework/commit/352c35a7aa3654e584f2c5884ec7b80b67cadaeb)
