### ISSUE TITLE
Email format is not properly showing in CC and BCC Email 

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#393]
**Description**  
when added a CC and BCC mail id is not showing email format properly CC and BCC email side

**How to reproduce**  
Step 1. Added a CC and BCC from the **admin side, agent side, and collaborator Side**.
Step.2: Now go to CC and BCC mail id and here are not showing properly message format.

**Possible Solution**  

**Additional context**  
When Admin and agent panel website:

![cc  bcc admin](https://user-images.githubusercontent.com/63539748/129019444-d35288a3-74d1-4cc0-a186-246bed69a517.png)

When CC mail id:

![cc SS 1](https://user-images.githubusercontent.com/63539748/129019494-7df13835-4bf2-437c-96ee-2e3f1178afed.png)

![cc SS](https://user-images.githubusercontent.com/63539748/129019498-27601c60-99c8-4f92-a118-868167c6248b.png)

when BCC mail id:

![bcc SS from cc side](https://user-images.githubusercontent.com/63539748/129019748-54c2c806-ecd6-427a-beb4-a6595aa12177.png)
[](url)

**Comment by Sanjaybhattwebkul** [comment]
@Komal-sharma-2712 

we  fixed this issue in master please check

**update [here](https://github.com/uvdesk/core-framework/commit/2725baa42f4b38e78b89f402395f30c0761a259a)**

**Comment by Komal-sharma-2712** [comment]
yes, I have checked this issue and now, this issue is fixed.
