### ISSUE TITLE
In Customer and Collaborator dashboard image not displaying of Admin Image

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#394]
**Description**  
when admin reply in customer or collaborator tickets thread so admin image is not displaying 

**How to reproduce**  
Step 1.  Create a ticket from the customer panel dashboard.
Step 2. Added a Collaborator using Customer.
Step 3. Now Replying from the admin panel.
Step 4. Now check the customer and collaborator dashboard. 

**Possible Solution**  

**Additional context**  
When Customer Dashboard:

![admin image not showing from cust panel](https://user-images.githubusercontent.com/63539748/129032960-1c0b7b9f-05e2-4641-ba43-e91a43ae20b4.png)

when Collaborator Dashboard:

![admin image not showing from coll  panel](https://user-images.githubusercontent.com/63539748/129033043-553ca4b4-53c6-46da-8436-ad21ce534d88.png)

When  Agent Side and admin Side View:

![agent side view for admin image showing](https://user-images.githubusercontent.com/63539748/129033806-95b58480-65f3-4306-b3a7-826fe95bd04d.png)

**Comment by Sanjaybhattwebkul** [comment]
@Komal-sharma-2712 
I followed all the steps given by you and the admin image is showing customer and collaborator both panel

![ccpanel-adminImage](https://user-images.githubusercontent.com/86394952/129160610-0a434658-dbd5-4b08-850f-bfa54f108a9f.png)
![customer-panel-adminImage](https://user-images.githubusercontent.com/86394952/129160624-d318639e-8382-4a3d-9663-a12b6e27e66a.png)

**you can see the screenshot .please check it again with a fresh project.  if you will get the same problem let me know**

**Comment by Komal-sharma-2712** [comment]
yes, I have checked this issue and now, this issue is fixed.
