### ISSUE TITLE
Agent Activity is not working properly from agent side

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#396]
**Description**  
Agent activity option is not working or not loading the page from the agent side.

**How to reproduce**  
Step 1. Login from the agent side
Step 2. Go to report option or search in agent activity so this page is not loading

**Possible Solution**  

**Additional context**  

when agent side login and click on agent activity:

![report option not load from agent side](https://user-images.githubusercontent.com/63539748/129184924-95982b08-ee55-4513-b058-b0b4dcf9904c.png)

<img width="960" alt="2021-08-12 (6)" src="https://user-images.githubusercontent.com/63539748/129185041-f94807fb-7816-4d65-a983-5b9c7380faf6.png">

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

As I check from Agent side to filter by date (Report). It is working fine.
I also added a screenshot here.
![Screenshot_73](https://user-images.githubusercontent.com/58874186/129186171-20e41be6-993d-483c-b0d1-38e01758d67a.png)

**Comment by Komal-sharma-2712** [comment]
Now  yes, I have checked this issue and now, this issue is fixed

![image](https://user-images.githubusercontent.com/63539748/130606302-4d91e99a-c2b1-41b0-a2b3-7c477c29c96e.png)
