### ISSUE TITLE
Translation is not showing properly in it(italian) language admin website and agent side view

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#397]
**Description**  
En to it is not properly translated from admin, agent, customer, collaborator

**How to reproduce**  
Step 1. Change to your language from en to it in above link : http://localhost:8080/helpdesk-project1/public/**_it_**/customer/ticket/view/41

Step 2. Now check your all option.

**Possible Solution**  

**Additional context**  
When go to knowledgebase -> Announcement option here shown in italian : 

![know  annou  bhar change h](https://user-images.githubusercontent.com/63539748/129186207-07f54bfc-1034-457c-ace1-431c0b42caeb.png)

when go to inner option here is not showing in italian:

![ann  not change](https://user-images.githubusercontent.com/63539748/129186309-5c63c767-fd75-4af8-83ed-2468e76f1902.png)

![announcement not change](https://user-images.githubusercontent.com/63539748/129186321-4b98d572-c67f-4452-a1ce-2414ecf9e171.png)

when go to Users->Agent->filter option : 

![agent filter not change](https://user-images.githubusercontent.com/63539748/129187401-f2c93149-cd25-4e95-8a9c-93ac77aca55a.png)

![agent in group option not change](https://user-images.githubusercontent.com/63539748/129187411-8a6d0a2f-56a2-422f-82a2-f9a41d4fa06c.png)

![agent status filter not change](https://user-images.githubusercontent.com/63539748/129187415-cf58c682-5329-4ad7-9b89-b762af2ef873.png)

![search agent filter in report option not change](https://user-images.githubusercontent.com/63539748/129187419-03a31fec-be76-4f35-bfdf-309b2b7fc9cb.png)

When go to Kudos option: 

![kudos option not change](https://user-images.githubusercontent.com/63539748/129187540-4f6a8766-96c3-4fe8-b2a4-22574b391820.png)

when go to in Privileges  section:

![privillages in advance setting not change](https://user-images.githubusercontent.com/63539748/129187935-9a730c8a-e10a-4cac-a206-aed5c6b934c2.png)

Now go to the Customer and collaborator panel:

![branding ss](https://user-images.githubusercontent.com/63539748/129188097-31197a1c-c2ba-4a66-96af-15270a1e16d0.png)

![subject not change](https://user-images.githubusercontent.com/63539748/129188107-1a145d1c-e949-419a-9b66-49230a128c94.png)

![T  from cust side](https://user-images.githubusercontent.com/63539748/129188111-15550af7-0ffc-4705-90fb-5c50908efa57.png)

![cust acc  details](https://user-images.githubusercontent.com/63539748/129188100-93564cca-b0b5-4c78-b554-3797632c6e60.png)

![folders name not change](https://user-images.githubusercontent.com/63539748/129188103-4b5d82f6-b7c3-4d66-b2c6-ca0e48832890.png)

![status spam](https://user-images.githubusercontent.com/63539748/129188105-3e586562-4e78-4087-950b-83c50b065c97.png)

When go to Article Section:

![art  not change](https://user-images.githubusercontent.com/63539748/129188263-b845512d-5f8a-460b-98f9-420de62ab935.png)

![whole art  not change](https://user-images.githubusercontent.com/63539748/129188272-b3694fbe-2422-4e01-9a31-b3961b21243b.png)

when Customer change details so notification is in en not in it language:

<img width="960" alt="when cust changes details our dashboard pop is en not it" src="https://user-images.githubusercontent.com/63539748/129188567-c34a459e-c38d-451a-98e6-ba828f9db31b.png">

**Comment by Sanjaybhattwebkul** [comment]
@Komal-sharma-2712  
   We've also done some changes related  the translation **[here](https://github.com/uvdesk/community-skeleton/commit/af44f5ae16e300e4e5d1adebde2fd4c0cf1ac8a2)**. please check

**Comment by Komal-sharma-2712** [comment]
Some More Changes do Here:

admin side note not change like below showing:

![admin-ticket-note not change](https://user-images.githubusercontent.com/63539748/129327058-04b7c880-0cab-4531-937b-11f0af62cb92.png)

when categories and marketing announcement save so green notification is not showing it:

<img width="960" alt="category pop up not change (2)" src="https://user-images.githubusercontent.com/63539748/129327560-f97b84ab-c501-418c-bc79-b3d6ca7fa242.png">

<img width="960" alt="mark annou  pop up not change (1)" src="https://user-images.githubusercontent.com/63539748/129327566-48af76ee-cd24-4137-9d2e-1809ba1b0048.png">


when go to kudos in filter option:
![in kudos filter grp,team not change](https://user-images.githubusercontent.com/63539748/129327800-aeae0259-fd30-48b5-b630-3d9871f0945d.png)

when go to knowledgebase -> artcles:

![articles-new art-seo in meta desc  not change](https://user-images.githubusercontent.com/63539748/129328213-6b979b1e-b343-405e-a275-d32a2a3a8a28.png)

![art-show-previous art not change close button](https://user-images.githubusercontent.com/63539748/129328214-7b1b6950-5efe-4e8c-abd6-429a00267715.png)

when go to knowledgebase->folders :

![folder-catg -preview button not change](https://user-images.githubusercontent.com/63539748/129328377-bbbcfbe5-d9ee-4328-9fc7-dfd6f9e967ee.png)

![know -folders option is not showing delete button](https://user-images.githubusercontent.com/63539748/129328382-5777ed1f-0c76-4530-97c2-958f65f34ced.png)

when go to Users->Agent->filter option :

![users-agent-filter not change](https://user-images.githubusercontent.com/63539748/129329203-8e5c8296-d46e-4d51-ab4e-655f6d8ed662.png)

![agent in group option not change](https://user-images.githubusercontent.com/63539748/129329933-894c6414-fb53-4672-982d-80b304e68e28.png)

![agent status filter not change](https://user-images.githubusercontent.com/63539748/129329943-4ab60809-38c0-46b7-9bda-481561bdb41c.png)

when go to prepared responses please check all options in action in status, priority, tags etc.. : 

![prep resp-action-priority choose and option not change](https://user-images.githubusercontent.com/63539748/129334215-95363575-5452-4308-908f-7ee1c518c1e4.png)

![prep resp-action-status choose and option not change](https://user-images.githubusercontent.com/63539748/129334219-abb3770e-feda-4bce-975c-1c061f46b1b9.png)

when go to the workflow please check all option check in action and condition option are not change in it : 

![wrkflow in action,cond not fully translated in it](https://user-images.githubusercontent.com/63539748/129334574-c225d5ea-14a3-4796-b943-6199c8e1236c.png)

when swift mailer and mailbox without filling save so error message in en not it:

![swiftmailer error msg not change](https://user-images.githubusercontent.com/63539748/129334835-0f2ea726-6441-4075-b407-63d3082a69ea.png)

![mailbox-newmail-setup error msg not change](https://user-images.githubusercontent.com/63539748/129334868-da630525-5563-419b-b752-e425825d6500.png)
