### ISSUE TITLE
Reply from collaborator gmail so collaborator name is not showing

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#399]
**Description**  
Reply from Collaborator Gmail side so admin, agent, customer dashboard not showing collaborator name but showing customer name and customer image.

**How to reproduce**  
Step 1. Add a collaborator any customer side in the ticket
Step 2. Now Reply from Gmail id of Collaborator 
Step 3. Now check-in agent, customer and admin dashboard

**Possible Solution**  

**Additional context**  
When Collaborator reply from gmail:

![image](https://user-images.githubusercontent.com/63539748/129672020-3bfa857e-cae2-48af-9844-50e749f67da5.png)

When Go to Admin Panel:

![image](https://user-images.githubusercontent.com/63539748/129672397-0d5c9ef1-d78b-4ef5-9323-641b0c58fe30.png)

When go to Customer Panel:

![coll  name not showing reply from coll  gmail](https://user-images.githubusercontent.com/63539748/129672475-fee50e54-767c-43be-9f74-0f2e8bd03f84.png)

When Go to Agent Panel:

![image](https://user-images.githubusercontent.com/63539748/129672881-3e144559-d172-4cd0-80ad-053fd5c380ed.png)

**Comment by Sanjaybhattwebkul** [comment]
@Komal-sharma-2712   We fixed this issue in master please check

**Comment by Komal-sharma-2712** [comment]
yes, I have checked this issue and now, this issue is fixed.
