### ISSUE TITLE
Undefined variable found when add reply to the ticket

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#4]
**### When the error comes ?**
If i tried to add reply to ticket by given below option then get error of undefined variable 'em'
![download 14](https://user-images.githubusercontent.com/43210406/49424429-962b4600-f7c0-11e8-97be-bd8b765316c1.png)

When add reply by any of these mark option
![screenshot 1](https://user-images.githubusercontent.com/43210406/49424463-af33f700-f7c0-11e8-9206-ec2fad7ad25e.png)

**Comment by papnoisanjeev** [comment]
fixed.
