### ISSUE TITLE
Remove from customer side image so default image not showing in Tickets thread

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#403]
**Description**  
Remove from customer side image and also admin side so default image not showing in admin, collaborator, customer, agent Tickets thread

**How to reproduce**  
Step 1. Go to Customer side and admin side of profile option and remove from the image of customer and admin image.
Step 2. Now go to Admin and Customer dashboard or website and check Ticket thread so showing break image instead of default image or avatar image.

**Possible Solution**  

**Additional context**  
When go to customer side and remove image:

![image](https://user-images.githubusercontent.com/63539748/130009717-747d5aa2-5c65-499b-869a-47cd69256e82.png)

When go to Admin side :

![remove from cust side in tt showing brk img](https://user-images.githubusercontent.com/63539748/130009771-3a95311f-53f3-4761-94e1-e5861b9b7a5b.png)

**Comment by Komal-sharma-2712** [comment]
When going to the admin side in customer option:

![image](https://user-images.githubusercontent.com/63539748/130010355-341cefc1-d4e0-46f5-b138-492bec283d8d.png)

**Comment by Sanjaybhattwebkul** [comment]
@Komal-sharma-2712  WE fixed this issue in master please check

**Comment by Komal-sharma-2712** [comment]
yes, I have checked this issue and now, this issue is fixed
