### ISSUE TITLE
When Reply added with only single BCC not added CC or collaborators showing error

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#419]
**Description**  

**How to reproduce**  
Step 1: Go to Agent and also Customer panel.
Step 2: Now added only 1 bcc nothing else like collaborator and cc.
Step 3: Now click on the reply button so here showing error.

**Possible Solution**  

**Additional context**  
When reply added only 1 bcc from agent and admin side:
![image](https://user-images.githubusercontent.com/63539748/132165354-83564d26-ea4a-4979-bbef-3376bc8cb50d.png)

When reply added only 1 bcc from Customer side:
![image](https://user-images.githubusercontent.com/63539748/132165877-01cacd7d-33be-4be4-89e9-f0c3c8336325.png)

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 
Not found Please check again

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712
fix this in master, Please check

**Comment by Komal-sharma-2712** [comment]
Yes i checked this issue and now this issue is fixed in master.
