### ISSUE TITLE
When Added Single BCC from customer, agent side so not going to any mail of bcc mail id

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#420]
**Description**  
When Added Single BCC from customer, agent side so not going to any mail. 

**How to reproduce**  
Step 1: Go to admin side and added a bcc mail
Step 2 : Same as go to customer side added a bcc mail
Step 3: Now check BCC mail id so here are no showing any mail regarding bcc 

**Additional context**  
When added BCC:
![image](https://user-images.githubusercontent.com/63539748/132295385-1f4621fa-6932-4909-b69a-126c2b82d305.png)

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 
fix this in master, Please check

**Comment by Komal-sharma-2712** [comment]
Yes, I am checked now this issue is fixed in master
