### ISSUE TITLE
Some files format attached with ticket thread are not download on agent/customer panel

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#43]
### files such as ( .xls , .ppt , .pptx , .docx , .csv ) are attach with ticket reply and click to get download each as single file but unexpected file will download like shown below : 

![screenshot 99](https://user-images.githubusercontent.com/43210406/50555843-d9150680-0cf7-11e9-9576-c96d35f73d39.png)

**Comment by papnoisanjeev** [comment]
fixed.

**Comment by vaishaliwebkul** [comment]
Still same issue while downloading files at customer panel

**Comment by vaishaliwebkul** [comment]
Warning is added with downloaded .svg file formate 

![screenshot from 2019-01-02 12-12-28](https://user-images.githubusercontent.com/43210406/50582341-dc3efc80-0e87-11e9-93c7-4d99ea3d0c72.png)

**Comment by papnoisanjeev** [comment]
fixed for customer panel as well. PR #30

**Comment by papnoisanjeev** [comment]
https://github.com/uvdesk/support-center-bundle/pull/30
