### ISSUE TITLE
When create Note for customer reply so agent mail  side showing note message instead of reply message

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#433]
**Description**  
When create Note for collaborator reply and coll create and also customer reply so agent side showing note message instead of reply message

**How to reproduce**  
Step 1: go to workflow create a workflow for note when a reply from customer and also a collaborator 
Step 2: Now reply from the customer side 
Step 3: now check mail of agent 

**Possible Solution**  

**Additional context**  
when showing agent mail  side:
![image](https://user-images.githubusercontent.com/63539748/134007823-e0d63a85-422e-4621-93c7-e03b92a6f553.png)

when admin side create a workflow:
![image](https://user-images.githubusercontent.com/63539748/134008978-a4c77eeb-f9e9-4479-80bd-987e34206139.png)

https://www.loom.com/share/79f8295483f446069c69d17d8683933f

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Check this issue again as i followed your given steps I didn't found this issue 

I also added screenshots here, Please check it again
In the first screenshot you can see I added a note in action where customer replied & agent get a notification mail
![Screenshot_8](https://user-images.githubusercontent.com/58874186/134325135-5b10a0ce-ac54-4030-8caf-76f960880d13.png)
In the second screenshot, I replied from the customer side
![Screenshot_7](https://user-images.githubusercontent.com/58874186/134325263-0e9727d7-6c7c-46cf-a37d-28611a378bd0.png)
In the third Screenshot Agent got a mail & In this mail, he only get the reply content, not the note which I added for the customer reply
![Screenshot_6](https://user-images.githubusercontent.com/58874186/134325402-2adf37f5-3391-401b-a6bf-a0837ede9c17.png)
In the last screenshot you can see admin side it is clearly see that Note added after reply added from the customer side
![Screenshot_5](https://user-images.githubusercontent.com/58874186/134325563-7506e39a-80e2-4ff9-a339-f5c2d743f121.png)

**Comment by Komal-sharma-2712** [comment]
@vipin-shrivastava 
I set up a new project and checked again but still same problem

**Comment by Komal-sharma-2712** [comment]
![image](https://user-images.githubusercontent.com/63539748/134371717-b8c51680-608c-48d1-a88c-e70238b6494b.png)

**Comment by Komal-sharma-2712** [comment]
I am checked this issue, and now this issue fixed in master
