### ISSUE TITLE
when  collaborator reply from web and mail side so not going to mail to agent mail id regarding customer added a reply

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#435]
**Description**  
when we use without workflow collaborator reply from web and mail side so not going to mail to agent mail id regarding reply from customer added reply because collaborator is also customer this ticket.

**How to reproduce**  
Step 1: go to admin side if you are created workflow regarding collaborators create and reply so doing disabled workflow
Step 2: Now go to customer side and  collaborator added 
Step 3: Now reply from collaborator dashboard and also mail side 
Step 4: Now check agent mail so here are not going to any mail regarding customer added a reply 

**Possible Solution**  

**Additional context**  
here attached video:

https://www.loom.com/share/08d1b035cccd47ab95d38bb6aca78479

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

If you want to get notified when the collaborator reply to the ticket then you can create a workflow from itself.

We have already provided some workflow, but as per user need he/she can create a workflow, So this is not a bug.
