### ISSUE TITLE
Apply Prepared response(action as delete ticket) to ticket then get error in a Development mode

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#44]
### **Test Scenario** 

1.   **Prepared Response Action :** 

![screenshot 1](https://user-images.githubusercontent.com/43210406/50556467-83dcf300-0cff-11e9-97a1-81b3cda75239.png)

2.  **Apply prepared response on the following ticket :** 
![screenshot 2](https://user-images.githubusercontent.com/43210406/50556535-665c5900-0d00-11e9-83ed-2844a71130d8.png)

### Bug : 
**errors shows :** 
![screenshot 3](https://user-images.githubusercontent.com/43210406/50556539-80963700-0d00-11e9-8a11-15783e542f7b.png)

**Comment by papnoisanjeev** [comment]
No need for delete action here..it  will be  removed from here.
