### ISSUE TITLE
Attachements not stored in the proper folder

### ISSUE THREAD

**Issue by cney-afluens** [uvdesk/core-framework#467]
**Description**  
Attachements are stored in public/assets instead of public/attachments

**How to reproduce**  
create a ticket with an attachment 

**Possible Solution**  
here is the patch

--- a/FileSystem/UploadManagers/Localhost.php
+++ b/FileSystem/UploadManagers/Localhost.php
@@ -11,18 +11,18 @@ use Webkul\UVDesk\CoreFrameworkBundle\FileSystem\FileUploadServiceInterface;

 class Localhost implements FileUploadServiceInterface
 {
-    const UPLOAD_DIRECTORY = 'assets';
+    const UPLOAD_DIRECTORY = 'attachments';

     private $container;
     private $requestStack;

**Comment by vipin-shrivastava** [comment]
@cney-afluens 

we have followed a structure to save images, files & zips in the assets & attachment folder.
If you want to save it in the same folder you can change the folder name in UPLOAD_DIRECTORY.
