### ISSUE TITLE
Create an articles choose numbered list not showing after click on view

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#469]
**Description**  
Create an articles choose numbered list not showing after click on view

**How to reproduce**  
Step 1: Go to your admin panel and create your folders and categories
Step 2: Now click on articles and here write some points and choose numbered list 
Step 3: Now save and check preview and here showing but not after click on view button 

**Possible Solution**  

**Additional context**  
When create articles from admin side and also agent side:
![numbered list - error-articles](https://user-images.githubusercontent.com/63539748/139442701-793ddff7-01f6-4a4c-a7c9-ceeefc79d486.png)

When click on preview :
![image](https://user-images.githubusercontent.com/63539748/139442877-c62cc162-6778-401b-af7d-90c14161acb9.png)

Now click on view button so here not showing numbered list:
![image](https://user-images.githubusercontent.com/63539748/139443010-34ff5cf1-0cf9-4dff-8ef9-204d354b2743.png)

When choose after heading after showing but not showing numbers:
![image](https://user-images.githubusercontent.com/63539748/139443523-a4c01c13-b951-4649-a4e8-d375aa5a818d.png)

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed, Please check
