### ISSUE TITLE
Go to agent panel showing more tickets option here showing total tickets number instead of agent assigned ticket numbers

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#471]
**Description**  
Go to agent panel showing more tickets option here showing total tickets number instead of agent assigned ticket numbers

**How to reproduce**  
Step 1: Go to admin panel and create some tickets
Step 2: Now assigned some tickets any agent
Step 3:  go to agent panel and click on more tickets option here should be show only agent assigned ticket but showing total number whole tickets

**Possible Solution**  

**Additional context**  
Admin Dashboard:
![image](https://user-images.githubusercontent.com/63539748/140900720-44790072-c4f8-4fb7-884d-c6fa1fe41ec8.png)

Agent dashboard:
![image](https://user-images.githubusercontent.com/63539748/140900980-e5ac6f65-9c13-4253-954e-4b280274af16.png)

![image](https://user-images.githubusercontent.com/63539748/140901103-9d3a4416-05cf-4311-b95c-b42eebac1984.png)

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 
Fixed, Please check
