### ISSUE TITLE
When ticket created from gmail side with adding inline images showing error

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#476]
**Description**  
When ticket created from gmail side with  adding inline images 

**How to reproduce**  
Step 1: Ticket create from gmail side with inline image ( some images copy and then paste it in message area)
Step 2: Now Refresh mailbox
Step 3: Go to customer mail and here showing ticket generated received mail here showing <img src> tag with many lines

**Possible Solution**  

**Additional context**  
Customer ticket received mail format:
![inline img-cust-ticket-created](https://user-images.githubusercontent.com/63539748/142617067-dca1f15a-8d2b-499f-b466-2dd78564cc03.png)

When this ticket assigned any agent:
![inline img-agent-assigned](https://user-images.githubusercontent.com/63539748/142617154-0dd922b5-35e3-4451-b15e-92806e41c437.png)

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed Please check
