### ISSUE TITLE
Add global placeholder in email templates 

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#48]
Add placeholders such as company logo, company URL and company name, also these placeholder should be shown for all selected action (i.e; nothing selected, ticket, user). 

company global placeholders must be shown only for placeholders list attached with email template body part not for subject part as shown below : 

![screenshot 13](https://user-images.githubusercontent.com/43210406/50583693-d568b780-0e90-11e9-99fd-e47bfbee7f6b.png)

**Comment by papnoisanjeev** [comment]
Added required placeholders.

**Comment by vaishaliwebkul** [comment]
Unable to open placeholders when select template for "ticket" then all placeholder's shows, please check
