### ISSUE TITLE
When we use prepared responses going to mail agent side showing Note message instead of ticket thread message

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#488]
**Description**  
When we use prepared responses going to mail agent side showing Note message instead of ticket thread message

**How to reproduce**  
Step 1: Create Add a note for customer reply 
Step 2: Create prepared responses 
Step 3: now ticket open on admin side and ticket assigned to an agent
Step 4: Now Go to the customer panel and reply from the customer side 
Step 5 Now go to admin panel and open a ticket and here shows Note added when customer reply on the ticket
Step 6: Now use prepared responses from the admin side and check agent mail id here showing note message instead of ticket thread message

**Possible Solution**  
When we use prepared responses going to mail agent side showing Note message instead of ticket thread message

**Additional context**  

When prepared responses apply on the ticket after customer reply added:
![image](https://user-images.githubusercontent.com/63539748/145148027-da6b9743-6bbf-4d62-9f63-f78a9d94a24f.png)

**Comment by vipin-shrivastava** [comment]
@fixed, Please check

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed & check still open this issue?
