### ISSUE TITLE
If we are using the registered same email id of customer and agent and delete agent so customer automatically deleted 

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#489]
**Description**  
If we are using the same email id of customer and agent and delete agent so customer automatic deleted 

**How to reproduce**  
Step 1: Create an agent with the same email id as the customer
Step 2: Create a customer with the same email id as the agent
Step 3: Now delete the agent and once a time not delete the agent 
Step 4: Now go to the customer option here are not showing the same email id of the customer

**Possible Solution**  
If we are using the same id of customer and agent and delete agent so the customer should not be automatically deleted. 

**Additional context**  
https://www.loom.com/share/a0c994aa99d941489e3f2b6e7958d4b9

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed Please check.
