### ISSUE TITLE
Folder picture not removed on the physical path of knowledgebase folder when deleting the folder

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#492]
**Description**  
Folder picture not removed on the physical path of knowledgebase folder when deleting the folder

**How to reproduce**  
Step 1: Go to admin panel and click on knowledgebase 
Step 2: Now create a folder with set the folder picture 
Step 3: Now delete this folder and check the physical path of the knowledgebase folder of your project

**Possible Solution**  
If we are deleting a folder so should be delete the picture from the physical path of the knowledgebase folder

**Additional context**

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed, Please check.

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed, Please check.
