### ISSUE TITLE
In Article when using duplicate slug value it save instead of warning message

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#495]
**Description**  
In Article when using duplicate slug value save instead of the warning message

**How to reproduce**  
Step 1: Go to the admin panel and create an article
Step 2: Here write in slug field option and write duplicate slug value you are used already in any blog
Step 3: Then save here not showing warning message like: **Warning! Article slug is not available.** 

**Possible Solution**  
If we use a duplicate slug value so should show a warning message like this: **Warning! Article slug is not available.** 
![image](https://user-images.githubusercontent.com/63539748/145524215-b252d117-7389-4bc4-bd9c-35b0d24e56d8.png)

**Additional context**

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed, Please check.

**Comment by Komal-sharma-2712** [comment]
@vipin-shrivastava 
I have checked this issue in slug value not take duplicate value but now create another issue after clicking on updating the article showing error and not updating the article

![image](https://user-images.githubusercontent.com/63539748/146003914-3df7f9c0-aa5a-4072-b955-db1b290631a2.png)

https://www.loom.com/share/263643ae227943538611721f738dbe2c

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed, Please check
