### ISSUE TITLE
Fetching E-Mails with IMAP will not work

### ISSUE THREAD

**Issue by Gill-Bates** [uvdesk/core-framework#498]
When I try to fetch my emails from my inbox, I receive the error:

`PHP 7.4`

`Uncaught ErrorException: Notice: Unknown: Can't open mailbox example.com: no such mailbox (errflg=2) in Unknown:0`

The reason is. that the `imap_open` function in Line 88 of `RefreshMailboxCommand.php` is wrong:

After changing to

    $server_host2 = "{" . $server_host . ":993/imap/ssl}INBOX";
    $imap = imap_open ($server_host2, $server_username, $server_password);

it works.

**Comment by vipin-shrivastava** [comment]
@Gill-Bates 

You don't have any need to add this `":993/imap/ssl}INBOX"` in the code. Add it directly in the **host field** from the mailbox setting.

you can see in the below screenshot.
![mailbox_host](https://user-images.githubusercontent.com/58874186/145759872-6b426bc8-32c8-46c2-8442-b1fb3055f96f.png)

**Comment by Gill-Bates** [comment]
When I create a mailbox, I am asked to provide an email address that will be used as the IMAP username. But since I have a mail hoster that works with a username, I get the error message.

**Comment by vipin-shrivastava** [comment]
@Gill-Bates 

Thanks, we will fix this & try to ask for an email instead of the username.

**Comment by vipin-shrivastava** [comment]
@Gill-Bates 

Some mail server requires us to provide **username@domain.com** so we are always used **username@doamin.com**.

**Comment by vipin-shrivastava** [comment]
@Gill-Bates 

Have asked for username/email in mailbox settings. closing this, If you still face this issue reopen this issue again.
