### ISSUE TITLE
In articles section meta title and meta keywords option validation properly not working

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#500]
**Description**  
In the articles section meta title and meta keywords option validation properly not working

**How to reproduce**  
Step 1: Go to the admin panel and click on the articles option
Step 2: Now create an article with fill meta title and meta keywords follow these points:

- Firstly time fill 255 characters and save it 
- Secondly, time fill more than 255 characters then save it, and here shows an error 

Step 3: Now you create an article again click on the edit button go to the meta title and meta keywords. Click on meta title and here showing warning after save that: This field contains meta title maximum 200 characters only

**Possible Solution**  
If we are write meta title and meta keywords more than 200 characters so should be show warning: This field contains a meta title maximum 200 characters only in first time not after save 

**Additional context**  
From admin side:
https://www.loom.com/share/cb8ca78b27f14db28b8c2c849836292e

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed, Please check
