### ISSUE TITLE
Website picture not removed on the physical path of website folder when replace the website picture

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#501]
**Description**  
Website picture not removed on the physical path of website folder when editing the website picture or logo picture

**How to reproduce**  
Step 1: Go to admin panel and click on branding
Step 2: Now set the website picture and check your website folder here showing a set picture 
Step 3: Now again replace the website picture so the first picture should be removed in the website folder but here not deleted from a website folder

**Possible Solution**  
If we are replacing the picture of the website logo so the first picture should be removed in the website folder

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed, Please check.

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed, Please check
