### ISSUE TITLE
Disabling Website has no Effect?

### ISSUE THREAD

**Issue by Gill-Bates** [uvdesk/core-framework#504]
When I disable the Website (Frontend) ...

![image](https://user-images.githubusercontent.com/25774289/145819183-9c9b4f1e-c362-449c-b02a-35fe4be3c2e4.png)

**... the Website is still working. Bug or Feature?**

![image](https://user-images.githubusercontent.com/25774289/145819341-31d2abac-8e17-457e-b9e0-0a54317c3c68.png)

**Comment by vipin-shrivastava** [comment]
@Gill-Bates 

After disabling the knowledge base from the banding section. It should not show the website page.

If it is still showing then it is a bug.

Can you please tell us which version of uvdesk are you using? 
Also, Share the screenshot of Table **uv_website_knowledgebase** from your helpdesk database.

**Comment by Gill-Bates** [comment]
UVDESK v. 1.018

Screenshot:

![image](https://user-images.githubusercontent.com/25774289/145821894-36c9862d-aa49-4c20-adfc-a87b60fbfb25.png)

**Comment by vipin-shrivastava** [comment]
@Gill-Bates 

delete the row id 2,3 from Table uv_website_knowledgebase and then again try to update the status from the wesite and check again.

**Comment by Gill-Bates** [comment]
After Deleting the two Rows, an 404 is thrown. uvdesk should fetch this case like "Website disabled"

![image](https://user-images.githubusercontent.com/25774289/145823524-39cf8548-83bc-4ed7-8995-939f5b33c8b7.png)

**Comment by vipin-shrivastava** [comment]
@Gill-Bates 

Because you are disabling the knowledgebase in dev mode that is why it shows page not found error.

**Comment by vipin-shrivastava** [comment]
@Gill-Bates 

If you found this issue again after updating the branding section & also found other rows in Table **uv_website_knowledgebas**.
Please let us know.

**Comment by vipin-shrivastava** [comment]
@Gill-Bates 

Hope you didn't face this issue now. closing this issue, If still face this issue reopen this.
