### ISSUE TITLE
When editing on admin dashboard role of account owner showing error

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#514]
**Description**  
When editing on admin dashboard role of **account owner** showing error

**How to reproduce**  
Step 1: Go to the admin dashboard
Step 2: Click on the agent option and edit the role of account owner so after saving showing error

**Possible Solution**  
If we edit the account owner role so should easily edit this agent or admin 

**Additional context**  
Admin dashboard:
![image](https://user-images.githubusercontent.com/63539748/146752324-42e43869-fdf6-44e5-ada8-e985faf199cf.png)

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 
Fixed, Please check

**Comment by Komal-sharma-2712** [comment]
@vipin-shrivastava 
I have checked with the new updated code this problem solved but the admin role changed **account owner -> administrator** so it is should not change role after editing admin groups and teams.
