### ISSUE TITLE
When use saved replies in {%ticket.link%} tag so this tag going to admin panel instead of customer panel

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#515]
**Description**  
When using saved replies in {%ticket.link%} tag so this tag going to the admin panel instead of the customer panel.

**How to reproduce**  
Step 1: Go to the admin panel and click on saved replies
Step 2: Now create saved replies with this tag  **{%ticket.link%}**  and save 
Step 3: Now apply this saved reply on customer tickets and check customer mails this ticket link going to the member panel instead of the customer panel.

**Possible Solution**  
If we use this tag and after check customer mail so this tag and link should go to the customer panel

**Additional context**  
When create saved reply from admin side:
![image](https://user-images.githubusercontent.com/63539748/146771784-afd6e874-d365-467b-83a9-de8446ccf055.png)

When go to customer mail:
![image](https://user-images.githubusercontent.com/63539748/146771984-c1251d47-3ab3-4b6b-a345-427c23bb3553.png)

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed,  Please check
