### ISSUE TITLE
In privileges showing extra option: Can manage Group's Saved Reply so this option should be removed

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#517]
**Description**  
In privileges showing extra option: **Can manage Group's Saved Reply** so this option should be removed

**How to reproduce**  
Step 1: Go to the admin panel and click on the privileges option
Step 2: Now this option is extra because saved replies automatically show when installing the project from the agent side.

**Possible Solution**  
This option does nothing work here so this option should be removed from here.

**Additional context**  
![image](https://user-images.githubusercontent.com/63539748/146880626-39766f31-0b26-44ef-92ec-0cab0c018d1a.png)

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed, Please check
