### ISSUE TITLE
If we delete the tickets from trashed option so not delete all tickets from trashed option

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#518]
**Description**  
If we delete the tickets from the trashed option so not delete all tickets from the trashed option

**How to reproduce**  
Step 1: Go to the admin dashboard and delete some tickets 
Step 2: Now check trashed option and select all tickets and click on the delete forever button
Now here delete only the first ticket not all tickets 

**Possible Solution**  
If we are deleting all tickets at one time so delete all tickets in one time 

**Additional context**  
https://www.loom.com/share/238e2720e38242c5a580c8e9dd60767e

After showing this error:
![Trashed-issue](https://user-images.githubusercontent.com/63539748/146907796-20a7ef97-0171-4a1f-86c1-9567d413b613.png)

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed, Please check
