### ISSUE TITLE
When giving privileges to agent: can manage agents so agent should not change permission of account owner

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#520]
**Description**  
When giving privileges to agent: **can manage agents** so the agent should not change the permission of account owner

**How to reproduce**  
Step 1: Go to admin panel and create agent give with this privileges: **can manage agents**
Step 2: Now go to the agent dashboard and click on agents and edit the role of the account owner  
here showing 3 options: **General, Groups and Permission** 
The General and group option is right but the **permission** option should not be here because this option here from the agent side and the agent edit the account owner so from the admin side role is changed from **account owner -> administrator** 

**Possible Solution**  
If we edit from the agent side so in **account owner role** should not show the permission option 
https://prnt.sc/23yszua

but other agents and administrators roles should be shown
https://prnt.sc/23yu8jb

**Additional context**  
If edit from agent side so change the role of admin: **account owner -> administrator** 
![image](https://user-images.githubusercontent.com/63539748/147037393-3ce552e6-aa71-4a86-867c-3eb281c5017b.png)

After that from admin (account owner) shows the edit and also delete button but this should not be shown.

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed, Please check
