### ISSUE TITLE
When using description more than two words then showing description value in ticket view list when choosing ticket type

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#525]
**Description**  
When using description more than two words then showing description value in ticket view list when choosing ticket type

**How to reproduce**  
Step 1: Go to the admin panel and click on the ticket type 
Step 2: Now write more than two words of name and description of ticket type and save it
Step 3: Go to ticket view dashboard and open a ticket now select ticket type so here showing description value instead of the ticket type name and ticket type name is not completed showing when using two words in the tickets type name

**Possible Solution**  

- If we use more descriptions so here should be not shown the description of ticket type.
- If we use two words in the ticket type name so here should be shown the complete name of the ticket type.

![image](https://user-images.githubusercontent.com/63539748/147212689-c336074c-3d62-4d88-9409-72efc9b5adb6.png)

**Additional context**  
When creating ticket type from the admin side:
![image](https://user-images.githubusercontent.com/63539748/147211347-33eb8042-3742-4225-9424-230c8147c8fe.png)

Here write two word ticket type name:
![image](https://user-images.githubusercontent.com/63539748/147212497-84f0154f-7a44-4f5c-8e31-8a7946fe60f0.png)

After go to ticket showing description of ticket type:
![image](https://user-images.githubusercontent.com/63539748/147211547-8e038630-d6e7-47d1-a61b-7c13196723d4.png)

Here not showing complete name of ticket type
![image](https://user-images.githubusercontent.com/63539748/147212548-170aa181-a36d-4de3-996f-8a6a5af938e1.png)

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed, Please check
