### ISSUE TITLE
In saved reply, more than 255 characters show an error instead of warning message

### ISSUE THREAD

**Issue by Komal-sharma-2712** [uvdesk/core-framework#529]
**Description**  
In saved reply, more than 255 characters show an error instead of the warning message: **Must be less than 255 characters** 

**How to reproduce**  
Ste 1: Go to admin panel and click on saved replies 
Step 2: Now write more than 255 characters  in the **name** field and save here showing an error

**Possible Solution**  
If more than 255 characters should be shown a warning message:  **Must be less than 255 characters** 

**Additional context**  
When write more than 255 characters showing an error: 
![image](https://user-images.githubusercontent.com/63539748/147320779-12c99a6c-d2f6-4f77-aa5b-0f9de6e0cb77.png)

**Comment by vipin-shrivastava** [comment]
@Komal-sharma-2712 

Fixed, Please check
