### ISSUE TITLE
Currently active agents

### ISSUE THREAD

**Issue by francog54** [uvdesk/core-framework#533]
**Description**  
I can't see currently active agents on tickets

**How to reproduce**  
- Go to a ticket view

**Additional context**  
![image](https://user-images.githubusercontent.com/6403273/147937157-a964f337-80a0-4b6b-be6d-15f2cf48fda7.png)

**Comment by Komal-sharma-2712** [comment]
@francog54 
This feature is not available in opensource and in saas uvdesk also this feature is not active at this time.

We are closing this issue
if still, you are any doubt you can reply on the same message thread.
