### ISSUE TITLE
Attachment's are not received on agent's mail

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#54]
### Steps follow to find bug : 
**Ticket Reply by customer mail receives to agent 
Reply by customer is added by attaching files, which mail is received by agent but not found files**

**Also placeholder <% ticket.attachments %> is mention in email template still attachments not received.**
![screenshot 21](https://user-images.githubusercontent.com/43210406/50635642-015f6800-0f79-11e9-9928-c91e73ae4ee6.png)

### **ticket reply on agent mail :** 
![screenshot 22](https://user-images.githubusercontent.com/43210406/50635724-50a59880-0f79-11e9-8e92-074815fa1506.png)

**Comment by papnoisanjeev** [comment]
fixed

**Comment by vaishaliwebkul** [comment]
My agent not receive any attachment added by customer, even workflow set.

**Comment by vaishaliwebkul** [comment]
if {ticket.attachments} placeholder removed from email template then still attachment added into a mail
