### ISSUE TITLE
The ticket counts are confusing

### ISSUE THREAD

**Issue by wolverline** [uvdesk/core-framework#560]
If you click on My Tickets, it only displays Open tickets on the right-hand side.

It is not intuitive at all. It needs to either specify this behavior or add "All" link and remove the link on My Tickets (any top item link for that matter). 

![Untitled](https://user-images.githubusercontent.com/460865/160891582-5612c291-f7d4-496c-b648-d12cfa59eac1.png)

**Comment by Komal-sharma-2712** [comment]
@wolverline 
Please check all status some tickets are in your resolved, closed, or spam.

If you click on open status so here it shows only open status tickets:

![image](https://user-images.githubusercontent.com/63539748/160984005-c0df2126-4f8b-4429-98c7-7974e00c2342.png)

and you click on answered or any other status so here shows only answered tickets:

![image](https://user-images.githubusercontent.com/63539748/160984035-812b993f-05cf-4f53-9dcb-c4aebcfab897.png)

and in my tickets option shows only the total tickets of my ticket of all status.
