### ISSUE TITLE
Wrong saved replies pagination results

### ISSUE THREAD

**Issue by BrianVB** [uvdesk/core-framework#568]
**Description**  
The pagination on the saved replies page in the backend (member/saved-replies) is representative of ALL saved replies in the database and not the  ones that the user has access to. That means if an admin user does not have access to some saved replies, the pagination will be wrong and some pages will display fewer, and maybe no saved  replies.

**How to reproduce**  
Create two admin users. Have one add ten saved replies. Have the second add ten saved replies. Go to the page to view saved replies while logged in as the first or second user and use the pagination to switch pages. One page will appear empty for both users.

**Possible Solution**  
In the savedRepliesXhr (https://github.com/uvdesk/core-framework/blob/master/Controller/SavedReplies.php#L139) include data in the request for the currently logged in user. In getSavedReplies (https://github.com/uvdesk/core-framework/blob/master/Repository/SavedRepliesRepository.php#L15) add in a check for a user ID, and if one is present add a condition to the query that will only request saved replies for that user. Or, mimic the behavior in UserService::getUserSavedReplyReferenceIds() (https://github.com/uvdesk/core-framework/blob/master/Services/UserService.php#L753) that will filter out results that do not apply to the specified user depending on the owner of the reply, its shared groups and teams.

**Comment by Komal-sharma-2712** [comment]
This issue is fixed now in the latest release (Uvdesk v1.1.1) so we are closing this issue.

If you have still the same error so reply in the same thread.
