### ISSUE TITLE
Menu option 'Create Ticket' not checking authentication until submittal causing a lost of the ticket form data.

### ISSUE THREAD

**Issue by stecca21** [uvdesk/core-framework#570]
I'm a developer working on the member side of uvDesk. If I leave my browser window open on an existing ticket or the ticket list past the auto-logout period and then use the user menu to create a new ticket I'm able to fill the whole form out. When I submit the new ticket I'm redirected to the login page, causing all my form data to be lost. This makes for a poor experience.

Authentication should be verified before displaying the ticket form as well as on submission.

**Comment by vipin-shrivastava** [comment]
@stecca21 

For this, you can increase the session time.

**Comment by Komal-sharma-2712** [comment]
@stecca21 

You can increase the **session time or logout time** follow this [link](https://forums.uvdesk.com/topic/1891/how-to-increase-session-expire-or-logout-time)

Now we are closing this issue if you have any doubts so reply on the same thread.
