### ISSUE TITLE
Saved replies removed when administrator deleted

### ISSUE THREAD

**Issue by komal-sh-27** [uvdesk/core-framework#572]
**Description**  
Saved replies removed when administrator deleted

**How to reproduce**  
Step 1: Create an administrator and save

Step 2: Now login with the newly created administrator

Step 3: After login new admin clicks on saved replies and creates and shares with any agent and another admin

Step 4: Now delete this newly created administrator from another admin side

Step 5: Click on saved replies here saved replies will be removed automatically from the agent and admin side

**Possible Solution**  

If we delete any admin so saved replies should not be removed automatically from another agent's side.

**Comment by papnoisanjeev** [comment]
Saved replies connected to user who is creating it.
Once the agent got deleted then all association will also remove.
