### ISSUE TITLE
When mail reply from mail to group and team side so email reply creates a new ticket

### ISSUE THREAD

**Issue by komal-sh-27** [uvdesk/core-framework#599]
**Description**  
When mail reply from **mail to group and team side** so email reply creates a new ticket

**How to reproduce**  
Step 1: Go to the admin panel and edit the workflow of the create ticket:

![image](https://user-images.githubusercontent.com/63539748/188876902-320d9463-c385-48cb-9f02-0056a772dfa2.png)

Step 2: Now email checks the **mail to group and mail to team emails** and reply from the email side:

Step 3: Now run the email refresh command and here create a new ticket from the **mail to the group and team email templates** side:

![image](https://user-images.githubusercontent.com/63539748/188877534-afd4f542-069a-4133-ba2f-b73b3654fd7d.png)

**Possible Solution**  
If we reply from the mail to group and mail to team should be added in the same ticket thread in the same ticket:

![image](https://user-images.githubusercontent.com/63539748/188878155-cf8b8e63-9861-4f00-be95-3d9f0825ed24.png)

**Comment by papnoisanjeev** [comment]
If any CC bcc or any user which is not a direct customer or collaborator on ticket.
If they reply it will not count in same ticket instead will generate a new one as those people are not directly associated on ticket.
