### ISSUE TITLE
When mail reply from cc and bcc in the received email notification so email reply creates a new ticket 

### ISSUE THREAD

**Issue by komal-sh-27** [uvdesk/core-framework#607]
**Description**  
When mail reply from cc and bcc in the received email notification so email reply creates a new ticket 

**How to reproduce**  
Step 1: Add a **cc, bcc** from the **admin or customer** side:
- With agent id
- With non-agent id

Step 2: Now check the cc and bcc email notification and reply to this email notification:

![image](https://user-images.githubusercontent.com/63539748/191685300-470223c2-285e-4872-984d-89fcd1bd6d71.png)

Step 3: After the refresh mailbox command this **mail reply creates a new ticket** instead of the added in the same thread message:

![image](https://user-images.githubusercontent.com/63539748/191686670-f1f62504-7555-447d-a812-a124b1f59018.png)

**Possible Solution**  
If we mail a reply from the cc and bcc side should be added in the same ticket thread instead of the creates a new ticket

**Comment by papnoisanjeev** [comment]
CC and BCC people just receive an email and those are not real customer for that particular ticket.
only replies created by ticket customer and collaborator email will add on same ticket.
