### ISSUE TITLE
error ticket creation

### ISSUE THREAD

**Issue by leooxx** [uvdesk/core-framework#618]
Hello,

I have an error when i create a ticket caused a dump line 281.
When i remove the line, everythink work !!

Error :
{"message":"Uncaught Error: Call to a member function getMessage() on null","context":{"exception":{"class":"Error","message":"Call to a member function getMessage() on null","code":0,"file":"/web/www/uvdesk/vendor/uvdesk/core-framework/Controller/Ticket.php:281"}},"level":500,"level_name":"CRITICAL","channel":"php","datetime":"2022-11-28T16:13:00.221746+01:00","extra":{}}

File
https://github.com/uvdesk/core-framework/blob/12a33bdda657e829abd3bfb2edc0d41bcba7b165/Controller/Ticket.php#L281

Thank you,
Léo

**Comment by Komal-sharma-2712** [comment]
@leooxx 

Thanks for reporting, we will update this line.

**Comment by grycroft** [comment]
The dump is calling getMessage before the catch statement which is fixed in master as stated by @leooxx but this file is still yet to be included in the latest release months after. Please could this be put into the next version release.

**Comment by Komal-sharma-2712** [comment]
Thanks for updating, we will try fixed it in the next release.

**Comment by Komal-sharma-2712** [comment]
Now this line is updated in the uvdesk latest release v-1.1.3, so we are closing this issue.
