### ISSUE TITLE
Unrecognized option "support_email" under "knp_doctrine_behaviors". Available options are "default", "site_url", "upload_manager".

### ISSUE THREAD

**Issue by blckhwk** [uvdesk/core-framework#631]
Hi,

This was the result of running this command

![image](https://user-images.githubusercontent.com/7903090/223007113-4aa61c94-3e89-44aa-8eb2-d809f0574c65.png)

after running php bin/console c:c, i got the error prompt below

![image](https://user-images.githubusercontent.com/7903090/223010455-d44b9781-ab68-4c77-b4b3-e414c1bd91b9.png)

BTW i'm running uvdesk-opensource

**Comment by blckhwk** [comment]
Here is my issue why I run those codes above

![image](https://user-images.githubusercontent.com/7903090/223018708-6541d4ac-13f8-430b-86b7-4d985b12c4ce.png)

**Comment by Komal-sharma-2712** [comment]
> Here is my issue why I run those codes above

Thanks for reporting this issue. We are already know this issue but at this moment, this issue is not resolved. We will try this issue fixed in our next release.

Thanks for your time and patience!!!
