### ISSUE TITLE
Disable ticket types shows on the ticket type drop down list in backend

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#65]
**Ticket type which are disable show in the ticket type drop downlist in backend i.e;** 
1. At admin panel , ticket create form
2. ticket list, mass action for ticket type
3. In ticket detail contains ticket type information

**List of Ticket type :** 
![screenshot 44](https://user-images.githubusercontent.com/43210406/50813946-f5d7bc80-133d-11e9-8299-3f75a9822987.png)

**Bug found : Disable ticket type shows** 
1. ![screenshot 45](https://user-images.githubusercontent.com/43210406/50813966-04be6f00-133e-11e9-9be8-4690f7cd00c1.png)

2. ![screenshot 46](https://user-images.githubusercontent.com/43210406/50813999-228bd400-133e-11e9-8fe5-2c2e81d60929.png)

**Comment by vaishaliwebkul** [comment]
**Disable ticket type still showing on ticket create form page at admin panel :** 
![screenshot 87](https://user-images.githubusercontent.com/43210406/51248703-04b21500-19b7-11e9-9f56-fd3bd90b6e83.png)

**Comment by papnoisanjeev** [comment]
Fixed
