### ISSUE TITLE
Apple / iCloud Mail Reply Causing New Ticket to Generate

### ISSUE THREAD

**Issue by kylebial0** [uvdesk/core-framework#685]
**Description**  

I am receiving a very similar issue to #607, but it does not involve CC/BCC. This issue is caused when there is a reply from an end user who is using apple mail.

The end user had been using apple mail for their gmail account on an iPad. I was able to reproduce this issue on my end. 

I had gone through the previously closed issues, but did not see anyone specifically mention the Apple mail application being the root cause of this issue, only the @mac.com domain (which was also likely using apple mail???)
**How to reproduce**  
1. On apple iPad, open the mail app that is logged in with a gmail account
2.  Reply to the email, and do not put anyone in CC / BCC
3.  Send the reply
4.  A new ticket will be created in UVdesk that shows the original email that they are responding to, image below (redacted)
![Screenshot 2023-08-01 143401](https://github.com/uvdesk/core-framework/assets/109872188/aaf4f245-a4b7-4ecc-9eb2-1a71698899b1)
**Possible Solution**  
I have not found a solution to this issue. From what I can tell, gmail, outlook, and outlook for web work as you would expect. I do not have other Apple devices, so I am unable to test on the mac version of mail.

**Additional context**

**Comment by Komal-sharma-2712** [comment]
@kylebial0,

You have created a duplicate issue. Here is your reported same [issue](https://github.com/uvdesk/community-skeleton/issues/688). So we are closing this issue. 

Thanks and Regards
Uvdesk Team
