### ISSUE TITLE
dashboard kudos not show count score 

### ISSUE THREAD

**Issue by chonnuchajo** [uvdesk/core-framework#697]
![image](https://github.com/uvdesk/core-framework/assets/62642745/751ac57b-27e7-4518-9280-43484fc5a82c)

why system not show count score

**Comment by Komal-sharma-2712** [comment]
@chonnuchajo 

Let us know, In given kudos list all tickets are status is closed or some tickets are in open, resolved, pending, answered, or spam status.

If ticket status is closed. If you want fix this issue so you will be some changes in your project. Please follow the below steps:

Step 1: Open this file **TicketRatingRepository.php** under your project follow the below path:

`your-project-folder-name/vendor/uvdesk/core-framework/Repository/TicketRatingRepository.php
`

Step 2: Now comment the mentioned below line in public function **getRatingByStarCount** :

`->andwhere('t.status != 5')`

to

`// ->andwhere('t.status != 5')
`

![image](https://github.com/uvdesk/core-framework/assets/63539748/4d7e3c55-f670-4ec6-927d-5734ae6afb1c)

Step 3: Now **clear cache of your project** run the below command in your project root directory:

`$ php bin/console c:c`

For more reference you can follow this [commit id](https://github.com/uvdesk/core-framework/pull/666/commits/4f8bce757f1d9afbc77830d91e6f498f6f7ff587).

I hope this solution resolve your issue. If you have still facing the same issue then let us know.

**Comment by chonnuchajo** [comment]
> @chonnuchajo
> 
> Let us know, In given kudos list all tickets are status is closed or some tickets are in open, resolved, pending, answered, or spam status.
> 
> If ticket status is closed. If you want fix this issue so you will be some changes in your project. Please follow the below steps:
> 
> Step 1: Open this file **TicketRatingRepository.php** under your project follow the below path:
> 
> `your-project-folder-name/vendor/uvdesk/core-framework/Repository/TicketRatingRepository.php `
> 
> Step 2: Now comment the mentioned below line in public function **getRatingByStarCount** :
> 
> `->andwhere('t.status != 5')`
> 
> to
> 
> `// ->andwhere('t.status != 5') `
> 
> ![image](https://user-images.githubusercontent.com/63539748/273777231-4d7e3c55-f670-4ec6-927d-5734ae6afb1c.png)
> 
> Step 3: Now **clear cache of your project** run the below command in your project root directory:
> 
> `$ php bin/console c:c`
> 
> For more reference you can follow this [commit id](https://github.com/uvdesk/core-framework/pull/666/commits/4f8bce757f1d9afbc77830d91e6f498f6f7ff587).
> 
> I hope this solution resolve your issue. If you have still facing the same issue then let us know.

![image](https://github.com/uvdesk/core-framework/assets/62642745/28e4b3f5-6cbf-4f42-b3be-2f626a9fdc22)
 it's good. thank so much

**Comment by Komal-sharma-2712** [comment]
@chonnuchajo ,

Thanks for the updated here. Now we are closing this issue.
If you have further any query then you can reply on the same thread.

Kind Respects,
Uvdesk team
