### ISSUE TITLE
Enable or disable customer sign in option or ticket create options not worked

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#70]
**By moving to knowledgebase section :- options available to remove sign in button from knowledgbase will not worked if authorized user disable that option as shown below snap :** 

### Select for remove sign in button : -
![screenshot 52](https://user-images.githubusercontent.com/43210406/50960332-27da5180-14eb-11e9-9c95-04425d3f4e06.png)

### At knowledgebase it will not remove :- 
![screenshot 54](https://user-images.githubusercontent.com/43210406/50960976-a5529180-14ec-11e9-9d1d-b8ceba741dbc.png)

Also check same for the **ticket create option** and **Remove powered by uvdesk** option

**Comment by papnoisanjeev** [comment]
Fixed
