### ISSUE TITLE
can't insert picuture in ticket

### ISSUE THREAD

**Issue by chonnuchajo** [uvdesk/core-framework#700]
Dear support team 
when user create ticket and insert picuture in detail by copy&paste 
after that system is show error follower fig . I'm not sure something with wrong

thank you for everytime support from you 

![image](https://github.com/uvdesk/core-framework/assets/62642745/866411ea-574a-4e39-95ca-03a50409ccfa)

![image](https://github.com/uvdesk/core-framework/assets/62642745/7f9c5baa-d3df-47d4-8ffa-c0c50f5cd9ed)

**Comment by papnoisanjeev** [comment]
https://prnt.sc/GUCbiPm63-jH attachment can be add using add attachment.
