### ISSUE TITLE
Productivity and settings section icons are not listing sequencially as shown on dashboard

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#71]
### Sequence of icons available in productivity section on dashboard should also be same inside menu bar when open any of these available icon.

**Note list manner of icons :** 
![screenshot 56](https://user-images.githubusercontent.com/43210406/50962602-9ec61900-14f0-11e9-8712-9965951d92e5.png)

**Sequence should also match here :** 
![screenshot 55](https://user-images.githubusercontent.com/43210406/50962729-eea4e000-14f0-11e9-8aa3-c7b5e80b606e.png)

**Comment by papnoisanjeev** [comment]
fixed.
