### ISSUE TITLE
Icon of attachments not found when view ticket by clicking on quick view trigger icon

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#73]
Follow below steps to find issue in image icon : -

**Get ticket detail in which attachment are need to identify :** 
![screenshot 60](https://user-images.githubusercontent.com/43210406/50967102-2e71c480-14fd-11e9-8438-03e5c617902f.png)

**click on the icon below to get quick view detail about ticket :** 
![screenshot 59](https://user-images.githubusercontent.com/43210406/50967032-ece11980-14fc-11e9-9180-7ce87d636f48.png)

**Attachment icon are missing here :** 
![screenshot 61](https://user-images.githubusercontent.com/43210406/50967216-75f85080-14fd-11e9-95ce-cdc27b2fc9b6.png)

**Comment by vaishaliwebkul** [comment]
Still ppt and doc file  icon not shows.

**Comment by papnoisanjeev** [comment]
Fixed.
