### ISSUE TITLE
On the ticket list page, you will see the icon with each ticket, to get full detail about ticket, which is not worked 

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#8]
Go to ticket list panel, **click on the icon below as shown in image** ; by which we can get full information about that ticket also for the next ticket but unable to do so. 

![screenshot 2](https://user-images.githubusercontent.com/43210406/49581670-b140b600-f978-11e8-9b2b-6ba63973391b.png)

**Comment by papnoisanjeev** [comment]
fixed. added popup functionality.
