### ISSUE TITLE
mailbox not get successfully deleted

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#81]
When delete mailbox get an error warning ! 
![screenshot 70](https://user-images.githubusercontent.com/43210406/51026321-38a2ca00-15b4-11e9-8f20-2656e8720fdb.png)

But in file it's exist 

![screenshot from 2019-01-11 15-22-40](https://user-images.githubusercontent.com/43210406/51026562-c2529780-15b4-11e9-9777-7c6a0d82afbf.png)

**Comment by shubhwebkul** [comment]
resolved
