### ISSUE TITLE
Get error warning while edit existing mailbox

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#83]
mailbox edit : 
![screenshot 75](https://user-images.githubusercontent.com/43210406/51026896-94218780-15b5-11e9-85d2-1759358074a4.png)

Get warning that mailbox is already created : 

![screenshot 73](https://user-images.githubusercontent.com/43210406/51026917-a4396700-15b5-11e9-8917-3b102fc39b08.png)

**Comment by shubhwebkul** [comment]
This warning arrives when you use the email_id that is already registered with mailbox

**Comment by vaishaliwebkul** [comment]
This error occur when we edit and save mailbox without changing registered email details.

**Comment by shubhwebkul** [comment]
Hi Vaishali,
We have already resolved this issue

**Comment by vaishaliwebkul** [comment]
https://github.com/uvdesk/mailbox-component/issues/9
