### ISSUE TITLE
Thread action icon and profile navigation action icon is missing from admin panel

### ISSUE THREAD

**Issue by vaishaliwebkul** [uvdesk/core-framework#89]
**Project Install Case :** 

**1. Using php bin/console server:run
2. Using localhost/public_Url_of_project**

In both cases found issue that icons are missing as mentioned below: 

![screenshot 13](https://user-images.githubusercontent.com/43210406/51120545-5c2b7600-183b-11e9-8307-c19a1cec91db.png)

**Comment by papnoisanjeev** [comment]
fixed.
